---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-servers
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
  storageClassName: iscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-backups
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
  storageClassName: iscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-config
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: iscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crafty-logs
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: iscsi
