---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: secrets
components:
  - ../../components/common
resources:
  - ./external-secrets/ks.yaml