# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.35.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: jitsi-admin-secrets
stringData:
  JITSI_ADMIN_APP_SECRET: ENC[AES256_GCM,data:wLFgU5WC0ATP9+5e9VtVq4RguyGQsV+8g/eC8QQFhNM=,iv:hsR3bHznQXFktyv/5m6w8ZclzrNI2aNM3owquSq4Jnk=,tag:OxnzbSBL/FHQjymajbmH9g==,type:str]
  JITSI_ADMIN_CRON_TOKEN: ENC[AES256_GCM,data:vvC6pgkl9ELk2vo/0nQINPWXkP0hDor9LFFfIe1VDl0=,iv:eKgQYfq+plcpb98PeXEHzfeb9OA1BNzcrfYzubKwBQw=,tag:u1FASc+QUcySRVRyX+AUYA==,type:str]
  JITSI_ADMIN_JITSI_EVENTS_TOKEN: ENC[AES256_GCM,data:5qTPDNq2cWt3UKzESEPEcehcWDQ6yLXalt4jGIE0pRM=,iv:Kcrnsum87psUonxbfE4+O4Qge66qmisuCkUAQRyx2zY=,tag:9+o2o8mFe4PuRNfOQNPMAg==,type:str]
  JITSI_ADMIN_WEBSOCKET_SECRET: ENC[AES256_GCM,data:z4Wc17p4lDYCtJa4C/XRVpU2fUXDL1oF6wtbsKYHnqo=,iv:vuwFSzixLsyUBV8E0RF5hQjUwsK80rTLVa6VzgeHa9Y=,tag:p5udJ/KtGFnZ/MMkI9AJIg==,type:str]
  JITSI_ADMIN_RABBITMQ_PASSWORD: ENC[AES256_GCM,data:nYvKEQibkrEsAMt2kZfFKIPlRgbwUmee,iv:HBvPcvsWw4bjQtI5FosI/4y07R32aRHg1n02ukVj/sc=,tag:/+ZmsAp0LzHC4LpqfScEmw==,type:str]
  JITSI_ADMIN_RABBITMQ_ERLANG_COOKIE: ENC[AES256_GCM,data:YNGwDQpj+iDCNoo3svgKxuZWT1N5+vStcFtgUo9E4n0=,iv:fdfclCfFo6f65YE5RPW9QG3k0wM0gF5MIaCUJUXEeJ8=,tag:kFhdl5GRlylJ4T9qW//NQA==,type:str]
  LDAP_BIND_DN: ENC[AES256_GCM,data:BzTZPizZRhk=,iv:HtigOWBq2WQJUAmG+GNsG0KnBqN+lbdufflQJx6Gy4s=,tag:8Ahz+kmHgcvHSL6+po6uqQ==,type:str]
  LDAP_PASSWORD: ENC[AES256_GCM,data:tnjq5iVX1aY=,iv:oYbMpu7lnr7TWspCs+HrThKltQw1MHtqT481Z2lEfGE=,tag:ll4r7KTucsy2S4yaaKd3Jw==,type:str]
  LDAP_USER_DN: ENC[AES256_GCM,data:mlpzqVe/eD93WFMWEtDBUTaGQVGXZN7pg/a0yoyDL0mLd9NQLw==,iv:u9/GCsZbpA6JkCGGwOXxvOV/xyflgMvvG/1QoR1PT10=,tag:97WmgDvMKmZ+lQThAqzLSg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TWJJQzBOcGRHcUlyZ1dB
        TTlZWkdpaFJqY2dPY3JocVNBcDhEVXZGM2d3CmxNbWJTYm9KSFdNd1BDT01lQmNK
        VExzNGRMcGJ6MkhJM0w5ZWdobFhsa28KLS0tIEVNZ0JKQkIvUUZJQ2JoY0EyZ09T
        ejdJNVZyNVE5K2ZrZUYyVUtXM2FLV2cKcecuiWbauss9M2sFRz3j8u5GxZXFWrh0
        hXWg8ALjIKnRn+JPz8CkFpBA0fwdpngsreHu4HukEYZPS23UDq19ZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17kkjwh97ech8ky6sa05xnyuxr9gpqwdjq8wjqc55a2mu7mdv9s8qvdfxpv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-14T18:25:54Z"
  mac: ENC[AES256_GCM,data:QeCALTlrN133lEB9t80+8PsD0+9hIN0NW9H32ZGfrWwb4V2lUxT9yRc8GoZvotSb79VOaJRlXDcN9w2BK5eyyc0SGcOsDYTruFvBAwRm587vAl1brcnDYfQGZQtfs4f+dn17cYDsaiirBwrD1fI4swseQYLQ1UmFNL0TZn6xF8Y=,iv:AtBmdyF4LWkjMaVgs+QTuCyE+BmDLdZ2C09HN+99Zf8=,tag:NL0F1MjM+KcXYx3dpeZYXA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
