---
# yaml-language-server: $schema=https://schemas.gallay.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secret-manager
  target:
    name: zigbee2mqtt-secrets
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      data:
        Z2M_HEALTH_CHECK_USER: "{{ .Z2M_HEALTH_CHECK_USER }}"
        Z2M_HEALTH_CHECK_PASS: "{{ .Z2M_HEALTH_CHECK_PASS }}"
  dataFrom:
    - extract:
        key: home-assistant
