# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: ${APP}
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: ${APP_UID}
            runAsGroup: ${APP_GID}
            runAsNonRoot: true
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: docker.io/fallenbagel/jellyseerr
              tag: 2.7.3 # {"$imagepolicy": "flux-system:jellyseerr:tag"}
            env:
              TZ: "Europe/Budapest"
              PUID: ${APP_UID}
              PGID: ${APP_GID}
              DB_TYPE: "postgres"
              DB_HOST: "postgres.media.svc.cluster.local"
              DB_PORT: "5432"
              DB_USER: "${JELLYSEERR_USERNAME}"
              DB_PASS: "${JELLYSEERR_PASSWORD}"
              DB_NAME: "${JELLYSEERR_DATABASE}"
    service:
      main:
        type: LoadBalancer
        ports:
          http:
            port: 5505
            protocol: TCP
    route:
      internal:
        hostnames: ["${APP}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs: [{}]
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: jellyseerr
        advancedMounts:
          main:
            main:
              - path: /app/config
                readOnly: false
