---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr
spec:
  storageClassName: sonarr
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs.${SECRET_DOMAIN}
    path: "/media/services/sonarr"
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - nodiratime
    - nolock

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr
spec:
  storageClassName: sonarr
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
