---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: ethSel0
selector:
  match: glob("58:47:ca:72:00:f3", mac(link.hardware_addr))
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 192.168.1.1
link: ethSel0
---
apiVersion: v1alpha1
kind: LinkConfig
name: ethSel0
mtu: 9000
addresses:
  - address: 192.168.20.1/16
routes:
  - gateway: 192.168.0.1
