# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.35.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: jitsi-meet-secrets
stringData:
  JICOFO_AUTH_PASSWORD: ENC[AES256_GCM,data:tmXJAgfuWTwKrULkJpWYC1EE86PUOI++Rx7EuMVqt4Q=,iv:PIUmOQbxCId9bX8R+tMQT1ktpvZbXY3Jyuc0qUr4kmE=,tag:xUQxfwWiIAdPNBgNm5yk3A==,type:str]
  JVB_AUTH_USER: ENC[AES256_GCM,data:7N2U,iv:5ZIvGYnp+NyYmP4EWo97XhrGNmr72rWaF/hX5+VQDTU=,tag:DXffOmABwiKySZQKaMawkw==,type:str]
  JVB_AUTH_PASSWORD: ENC[AES256_GCM,data:fE0/fhTCQ7PXLm8s/WDZrzVMc6eRpiGi7cAweIdf/gw=,iv:FgSA7FTkOt/t8mj2PoKiwbamtzg40u5s5ilS2S+qHIA=,tag:D8nqbHQdyRiFek5VFn1/DA==,type:str]
  TURN_CREDENTIALS: ENC[AES256_GCM,data:BUKfGZsQbl/PVM6pSnQKC9V4wxSrZYK2trCnFSJMbDE=,iv:I19UPyQKp70u9/4SBgV1N8VV9srf7y310Fzhrc2ccSU=,tag:QDRYuF3TaigysHyXpD6pmA==,type:str]
  JWT_APP_SECRET: ENC[AES256_GCM,data:1BhbLaKovUXB6Usnq59R2pKcYumxLepf3ZHDrj1Z0iTnJLjTUWgFgtqGM1ZpnyNzoUMnNdqHrFd8iiAxUVl//Q==,iv:R5F22IOmQHqBz+uVtOt8LvCKGI90uCk0Hor4mL3n5R0=,tag:ILz/u8ksbFDMC2p//HFAAw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TlIzRDNEVnZFNXZPdUZK
        VDRRQmxJdGgrRktuZzN2TUxZS1RqSjN2OEZVCllHWnNWRThzY0RYV2JFUStWbk9h
        UDdpVW5hVWVuNmlVRFZGZk02bnJRamcKLS0tIG9jOE9nNjVNVGYwb3A0YVRVeElN
        dGR1bzU3bnF0ejcrMlJCK2tTTEhONWsKjxZ601bXWZp48BEzCdHvQyk0f2o+zl+J
        oGfYsjbTP1IVEUYv9TC7504sGxPA5JKDOAxxTgsL8NNwQ8ceqyCpTA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17kkjwh97ech8ky6sa05xnyuxr9gpqwdjq8wjqc55a2mu7mdv9s8qvdfxpv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-14T18:30:43Z"
  mac: ENC[AES256_GCM,data:9bFsupZA/q/90Dwy3LupHQqOhtKBlqw32oWRFRuCLxUnacvEDuu3PzdoKa+mpdWWqQu4o+xfp+/F+xZ+g1wgI0Cw1sSt77ibYRXuZIzYRU5UeqpF+LCYdr3fLMmsXgp4OB8R8YFOZSwIiUa6TFXl8jbiWVwlGx5mX2/eZugL5c8=,iv:WS3BE+ItRor6vLrTPpbXKoj7UFLGE9oVPCdAKriJPD0=,tag:pgdfgNHuodgiwhH4oG6IPw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
