# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.35.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: jitsi-meet-secrets
stringData:
  JICOFO_AUTH_PASSWORD: ENC[AES256_GCM,data:tmXJAgfuWTwKrULkJpWYC1EE86PUOI++Rx7EuMVqt4Q=,iv:PIUmOQbxCId9bX8R+tMQT1ktpvZbXY3Jyuc0qUr4kmE=,tag:xUQxfwWiIAdPNBgNm5yk3A==,type:str]
  JVB_AUTH_USER: ENC[AES256_GCM,data:7N2U,iv:5ZIvGYnp+NyYmP4EWo97XhrGNmr72rWaF/hX5+VQDTU=,tag:DXffOmABwiKySZQKaMawkw==,type:str]
  JVB_AUTH_PASSWORD: ENC[AES256_GCM,data:fE0/fhTCQ7PXLm8s/WDZrzVMc6eRpiGi7cAweIdf/gw=,iv:FgSA7FTkOt/t8mj2PoKiwbamtzg40u5s5ilS2S+qHIA=,tag:D8nqbHQdyRiFek5VFn1/DA==,type:str]
  TURN_CREDENTIALS: ENC[AES256_GCM,data:BUKfGZsQbl/PVM6pSnQKC9V4wxSrZYK2trCnFSJMbDE=,iv:I19UPyQKp70u9/4SBgV1N8VV9srf7y310Fzhrc2ccSU=,tag:QDRYuF3TaigysHyXpD6pmA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TlIzRDNEVnZFNXZPdUZK
        VDRRQmxJdGgrRktuZzN2TUxZS1RqSjN2OEZVCllHWnNWRThzY0RYV2JFUStWbk9h
        UDdpVW5hVWVuNmlVRFZGZk02bnJRamcKLS0tIG9jOE9nNjVNVGYwb3A0YVRVeElN
        dGR1bzU3bnF0ejcrMlJCK2tTTEhONWsKjxZ601bXWZp48BEzCdHvQyk0f2o+zl+J
        oGfYsjbTP1IVEUYv9TC7504sGxPA5JKDOAxxTgsL8NNwQ8ceqyCpTA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17kkjwh97ech8ky6sa05xnyuxr9gpqwdjq8wjqc55a2mu7mdv9s8qvdfxpv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-14T16:32:48Z"
  mac: ENC[AES256_GCM,data:1o2v24c65ZFc4Qdoiv9M5r3wLvxlgH1x5bI0mKV8Q/XZl3wmO2ia5kRIpeKtDd0shfxtgg2yscHy+5pukNcYLG5yzGEcMtr8YFck1qgV4frTb/BSlWulRT5h0gamTF8G+xzlDlDfqHSevBknCA4Pn/IrW+iVR2zK5FYKpnuuD4U=,iv:rh1WMrsqxVFQWBSYv8xz2p/4igyWpAH7qgW5EHByXBU=,tag:eBw9vkgJsqD96MLVfXT6pA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
