apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Mdwl5iqlKIIwCyIGlzVxIB9IpyCd/1y8ACKj9IAJZLKH9axYG/AiLw==,iv:JL65ySlwHnaPQ2Pzq+eIxErYgIGeh4f77XCuYYbXcHU=,tag:j7G7ail3G+KExQwcepFbJw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEpGUzVWOUVj
        MlByU1pjc0h0ZmZjdzVSSlJ0cFF1dlBBWDlHV1dTZERlOHBId1RGcUNOU3ZXTkZv
        cnhLYWd1SzQwd0U3VTF5c2JNQnduSG1IT3BiUkJGbTlXRC81V3ViWUg2M05pVlVR
        V3hyNEJxUTB5YjJWT09UYkdiMkNhM1ZSM2FmeXpSNk5oc0JDdW9LVFlkUE1EMzBt
        anVjVXBUbEcrczErMFpqMytEdXo5M0JXYTBmR2ZjcWdBclF5eFU3YjNVMElKdCt4
        djhpaUFCVGxQT3p3TmMyYzFxUHZ4N0tGV3N3TUNnWFpwUkJiRzBkOUE1emRnQWRD
        SkNMblc0d0VyT1NxN0dVUld0TEcwampxQ1E3YnN1cFkwWHd0aVZNWG81bVNyQS8y
        aWpGOE1kNkN6YXUxMUJjVmFSZ2lTZ1BNbGpKNmNLbWplaTJ6MTk0OG5ob2hobE9a
        YjdEdHhBamxYSDlDbGZLYjhZajlxaU1oQXBkamJwZnUyN3pqc3pSQTI5MmV6bVcy
        WEJkeG1xT3RQRkdrWnpSSTNHNU9pc0RWYThUb082WkNjb0kyTGpkcUFlUjdHMHJk
        OFdDNTdVS1gwYndtZDdrcVhGTGp1TjBDV1pySlBCRVVCMGROYXY4ZlcxY2JnclRQ
        WDlwaEg1Y1gzVmxYdUpFamVvSXFCd0NscUVpa0JBcWpnNmIxdDRjd3NHaDkvbmJt
        dG5tZzdIVzA5R0RieGpwTmVYMmxhTldIbVJPQnlHVVdqT2VTQjBRUDhkOXpEMVdM
        cjV2b2o5Ym1Nem5IZE1sMllnU09NTVBuVkkzNzAyTncra1JVdFY4WXhiZU9ZNWhq
        Y3hqTlRYTmU0OEpQWE1uWW1wNnc1SDBFWkVnZ1JXMXY0TWNteTFHb3ZZaUtCZUZy
        YlRiRkpDb3VVc01TZkYvSW5rNkpCUGMzajZYMjE5U3lGYkR2MDhzY2RQUTVzRnY2
        dzBxMEdIYjlYVExFek8vdVZsS09iWGJ1TklrVEkrWUhFckVZWjRkVS9oMm9nL0dT
        R0p3aVh6Y1NqRzRvazBsazJTMVh0STkxZ2VUdkR3NEdha0xDblg2MCtITDdLUzdD
        V0lDUjRKY2ZaQ2t6ZlN1SkJpOXlNYk5BMzFkSHpRbTU4M2pET0t6b01qN2N1Tldy
        WHFjUUFpZVpYZm1OazBYbWNHaUZ3UGROc05wd0psVVZ0d1hZc0tjMVhyY0JmdXJI
        SmZXRmRsM0NqdGQrcm4vQ2czWkRMYUV5YjZoaklWUjl3YlVxMGU4dGxZWUY4Mldq
        RXBldkpnaml3ZVF2blhQR1dQWW14Vng2c2VEOHBKQ0N0SzFrby9PRG4vTCs4UDdY
        a2EzNng1cy9LT25vNlQxNXo0UHF3MmYzdkNlUnZXSHlkemJKZjdDVS8yQ09VTTBI
        N29uMnp0L1BEa1dHczNudkFqWGtrT1ZRVEVXSVB5SVpMU3VEdVgyNysrM3lVbnlS
        Z0RvRHo2Q1pwVHhBc1p0bE4wWDJ5TW8zM2x2TUJMOXVuY0l1RzJDWDlPaGJRUGV2
        aVhZdkYrSHo4aGtYUTBvanF1eFJIbG5CamZsVFFrRGdzWjVycnBrSTNwa1A5MHlv
        Rjd4MiswMC83Z2lBTHA0MDk3azZrSXFUVWUxWWdKL3VKL25Tem9CNjFIME9jOEM4
        R2xzdUt5RWsvTmRCUUNuVExUUVVRQU9ucDZjOGtUbGJMbzZQUVEwL0RDWjdnZFo5
        RjQ5VVJEeGdlNTR5ZmZESFQ4ckJNQmRESnFTNTQ2MVFaWHhDa2UweXpOdU56elRq
        R3lwNHo1dS9PZFpseVdOYTA1a0s2R2NubXprbUNjaWFvbmhtdXExemgrT1dNdDlw
        eWE0MHdHVUFkeExHMGt4VGdSaXdZcys1Z2c2N0ZXQkZxRG4yWjN0MjBWTHFOdC9Y
        NGYzWjE0VkRXQzFCVk1MQzNxc0hEckRKV0F6Q2ZvbmRxWElwQUM3MUdnZm5hUQpq
        SjJ6aTVxdjNZOUZFTTNpQ3JyamRIRnJ1TzRGK0dYc3BpdUNydWdkc2d3Ci0tLSBY
        NjFxMU1SUktwb3B5bTd4ZkdDaDhQOWRFTEE2SVFWUkdJbkpCNkRSdDI0CqJPDpdR
        MJ2RlfH5ZGoBXxN6NKOOxeTGGymc/FSkc0COqCNlS2YICtMk6g1uWRChxG8Yxn5/
        SLWWZbzLnl6UACc=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14wqvmn43wc3tquc22uyme4sgy0kyswdzcqlqj5xax2ftqsdwfs24s8a48f8nc0k6xp8a844zq3x20sj3p5q4htg203sy0am3ccng7369nm0mfjqt5lp9f2grzjsev7ktyl0zj9puz260864l0kktswsgwrwr8jyw2jurxjs2f7ys8mpg8urxfjfw5wggyeskg5j34x32hhtnk2kpugj4k3vx07s3a7desr08rn46jk03mc4qhkdq76sf0jgy02m76uz9l5y7rjd34y4vy5znya3j5q8q74sq2pqffy7uxcxrctuzgywvwdwptwq9yehchmhskgt56yfhedgae0nt489n3ld824tf73efvsgset2kkdneqtaaqs5t2zzk072jal2eg60n3e7adrjwgkvpdr99jleckkm48g7urry8v35s47v32a5qa75yk486sz650vxnany0jxjrl69kzsx38d4sg8ph4ccsf5f3sqexqm7fds55ckk7s958v2uhcwcqguve2f2k82g5yfzz8n9kllzjw5y9y485xguawkw0clqh3k5s4a06jya2esejuxjatccf4jznf55f4xjvwjj52gg38l3ksa8jfp3mvxqy0324nkaslnm96k56ve0ekjung42jpwjmuhmrnq22ynmq8ffk2wv5rd5578gvtt09hqr0x9h0lznjy5s6p6q9xqfhpc05g5h9k63grec3amvny6y8jjkpfqgpuhxk24ejs93ech3s5ycqj3w3djs52x2pksu9lvczz66z49vruu2uus4tapncmkxm4p905j7qr2xq62z8df6vhf3ugxcekngqvc6g0y958s3vnzs9w6vaj0v4vddke4thuwr5rc033r7v8tgjg6jw6u3e7kqyfjqjnkdy5x3z9ww5d399fw6sjs5sf23lty4x6a6v9nyt4043yq6fprajg9rtu77x2qth6stfl896va5p59hcguv5079pmlgc25a8zuwrzhjvvxvarc5qjcgt7fa8h6aacr7jax529f68gv2vm37ejphlssxe928rkuezdzur7pzpem6e2jrrdqrvnq39mwd85lm5ncgkxdaz0d67mcza9msmerv8jfcs88y7w48zk4k9wutsasgfekdkjq9r23xgczgplvfga9hxzxm2z6xvmjmp7hquc95gmckpv5vzvux7hxjws2tl8z2vgm6vckhvq8rfljc9f0qdq6wy2w8sxl3mp25g5sd3h9afaa5ggd7g98wkryqh537a0faa359mh722seg6f0ssqwzm7y49vjvjra46yjc3zwqzp0ygc3gtnrrhs9yesm56frevzprd3yytqm4thv3fhdmexgv465a950xvlptk4s0hte6wzzskyj3scdtf0qjkjv25tn5ggc85wfadngz6jpjhjgm5c44ad3uqhgancst7f5dhw7dt5qs0q5p0ffaaejj9pv99fqegrypejzuuffhajpprtm9frx795umkwd2rgzhyxwnrez2z8yyvcctgenslapqq9uyzjk2t3hus43sfpxcg8fakques9kpy4v5pck4t2ajn8gtph3pquva984pqjq7mwxzh3sth5qdc722g5zztsxc90qy8sf4844p2k84kjv7jczymzhxvf2aqpfm2jgyze2qk8euzkx9l553nfaayue5el3dhyus8gu2cjfme4jzknl6p9zshr2cg4wfpz45t3xr2qh4tqplcvgqh0shye9rza2rek4j2ashjrrf4f8k7p2d32u6tq7v38j9jzn2lqw05m0q746q23kfvl2mxsyqant2uhg0fhzngete8kjcc0ughw7hluzklsqxwz3f5m9qvy9qrdfrmq22s7n4wqvrts3wtzhxpe09ngzlc76qmam7jlkrx59834ngt5w2j4wjk85wvrjrnzzra4nf2m2hdv8nswvhf39lr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T06:31:48Z"
  mac: ENC[AES256_GCM,data:Uw1J1eAs1hyHg374ESaTH0qdwLQManCpW1KMQUNP5IDeDiR19EnetbAwNiwwABpvRFI/1C/Rw89lszoM9BD3hVaQBTK7JJ9CnxZuAHD0Qeh4Cuv3XW6flomaNIuiIsk7h6ge9V1ctV8AagF0iaTTVGAPVi+qXo3G5DpgLUS/3iE=,iv:Cnh0ywBIXdHRonU1zK8V4sqIYiD6zmps3EL1H+G1bNQ=,tag:vnzyDJuI7t3sxIHStT6pQQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
