apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:EhK9mcq2OjBkkjV0CPeLVQ1H7UY8+1fNLgkWFFmvboW5IKZS4fjUsw==,iv:mMhtVAPFwhuYYXNEjOQwe/+HmEpdOqMA9cSty8trs2Y=,tag:AsdRrEg5oUvHX09NRaEAeg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFYrMFdsb2l4
        ck1aQm9obWZQVFVVTUUyU1BaUHNtUTVlaDR3Y1pwWmpQVjZWT2I0U2FJUFNSa3VZ
        MkJoQ2JmbkxwZVNHTzl6WmhiVkxZM3NDK3ZKaTg4RVhLRmpRM0R6V210T0dIUmJR
        dzg1OEdIalBzVjNFK0RkbGs4L2lCU3hCSndha09UM203ejZQVTBwZE9Vd2RGcXN4
        dTBYTDZIeFQ3aGJuZ3hvQ0J3V1AwMmRSSmN3VHA2OFB6TmNuak43bG5WZ1MweE54
        c2J0RGRwNkYxSklDUmRYdkVrb3piQ3NQM2E2aFZCVmhySVowMWx0QnB0eGdTMEwv
        WGxUcGp6M3B2bzJ4dU9HRDlycWlucEJITUc3QXdkNVpEQk42dWZ2RUZDL1Q0VzV4
        eGhLYm9SK1U5WVZIMEM1aFg4dm9vd3gzT0lFMXJjUUxEOHZwa2lxRzNPK01MME9T
        V0orRUYrT3hLbzBiQTl5bVQvTWNwZlJHaTdTRFZFYklCT2dGamU0VEMyNndVY0Y5
        SUhYL2xaZGlKaEF6ZGs3R3hRclNETGEvRkpiUzVkeFRjMC8wdzFNOGdRS04zbEJF
        WlZJcnRhNHIvZ3U5bFU5eWVBUDg1dTZ1Ni8zMENyWXpZNDdVSUYraHd2bXovcTk3
        R1Z0Q0dyMjZwRGNlYUNtM05CQkRRZEtOS0x5b0pFTWNYdVlVRmtKQVBuTS9nVFhn
        MXdNNEF6YklFRCtHUW5vMGlvdU5DS05QejM0ZG45ZnBzUFNpSDJPV0NaY2YycGNH
        bkZRRTkrL2QxVHlvNDBnd3AzTGhpb0F6SXoxaXJtT2VxQlNOWVVpZ0VGS1dJR1BU
        U2s3M3RKK1FmQWZVMDkrelJsU0Yzb1hsOGtrRk1ERWtFVTVvQmd5dlpucU9Yai85
        ZDVyVFgwU0o3SnlMRlQ2TFZabEplNGVFd0dXckZtMmkxbk1yZDA3MGtHTFpvQ1dW
        cTlZRWxKQ0JzSUJoVU01UXN6SjQ1VUY5cFBsZENWQVFnbnN1eEdCWTk1N01oM01B
        VFJzQVJIQlpaUWhYdUo1RXlkbzQrZWJUMnFZOFpmZG9NRGxncHlPd2w0eDRRYTFI
        aGd0L1p1R25WZU5SSmkvTEpSYUhLOVBRc1RCbGxPUDRDamxWOUl2Nm5WQ2NQZVcv
        WGZGWnBQNVhwcmNmNFRpM0pMd3BIL0dvQ3MwaEtmYXFUbmFzT0h6S1JDOC9TUUVm
        MzViN256NStuajFCYTNUeEJXYit1TGl6cEZzM2NtcW00Y1RxcERvb1VUa1k3NTlm
        bE95Nk9JMzBnaGd2M1FUeTNrUEM1eVhCSzM3ZmVJbk1GVTJYb0xrcjZFUmxJdTdR
        YldTNVAvTlB5NFFhK0RGVU9yZ29RVTAxSXJUUGYrVU1ydnNXbnBOZmsvOFEvOEp5
        YzlCbUJYa05sL1dFeVdaME1tc0VaLy9vVElIbys0SzN3UXVtd0Jud0VJMXBYQWZq
        TUFMdEZRSDUwNDJmRi9xbUsvVW9CMkxZcHVCZzB1WVNNQUZFZk5KZzZ5Vm1RY2pP
        UnJjc1EvYWJqMHpTTlhSRTFxSC9RSmoxVTAwSjMrNm9rRHJHNFVUSDhuMEFWaTlN
        S2hDS1dmNnhJZUI0Skl6TmNEaTlJazY5SldOb0FtUXVPMU5ublJmaFVVSnQ4dkFN
        R2taRERXcWlaTFJDTGZIMUI3N2NmRGMxclk0ck81TEp2b1dtbEpNNjcrSHVVcE8x
        UHI0MmFuNlpCZWZKLzYyRUFMc0NyMGFDWVRKYzBZdWhSL1pDdFE5NVpvRjVkMGRG
        aWpldnIySlpZcjQ5TGVTVTMwZnlHcUxHQTM1NEtyVkxXVm54VzgrRWMveW9MRUpx
        ZzRlWDhEZjQrdk1FOUJFTFhCVHpzY1pXQWg3d1lFbURPMHA5cStnSDRHbFg3U1dW
        a1dEZW0xWWVNQWlCaHgrSzNlSlBVQ3dtQmRtY0JORnlHNjMwZXMwNDFZcWhNUQpL
        akZJQnFTQk5qRUg2eVgybXU2b3RxNFUwQk5ZUDV2azBGTVVObXdKN2wwCi0tLSBZ
        WXRBVUpHM3ExV0Noc29zY1ZWMWVzTjROcFFWSjJuOWUxdUZ2Nk1RQnFVCrYbYRGl
        v+1+dum8XcRJLw/y+RKrZu802BI29sBeO8/4v06BJsr8Govnkmy/SJr87J40YLex
        q7gcR7qTjUpzPaY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14wqvmn43wc3tquc22uyme4sgy0kyswdzcqlqj5xax2ftqsdwfs24s8a48f8nc0k6xp8a844zq3x20sj3p5q4htg203sy0am3ccng7369nm0mfjqt5lp9f2grzjsev7ktyl0zj9puz260864l0kktswsgwrwr8jyw2jurxjs2f7ys8mpg8urxfjfw5wggyeskg5j34x32hhtnk2kpugj4k3vx07s3a7desr08rn46jk03mc4qhkdq76sf0jgy02m76uz9l5y7rjd34y4vy5znya3j5q8q74sq2pqffy7uxcxrctuzgywvwdwptwq9yehchmhskgt56yfhedgae0nt489n3ld824tf73efvsgset2kkdneqtaaqs5t2zzk072jal2eg60n3e7adrjwgkvpdr99jleckkm48g7urry8v35s47v32a5qa75yk486sz650vxnany0jxjrl69kzsx38d4sg8ph4ccsf5f3sqexqm7fds55ckk7s958v2uhcwcqguve2f2k82g5yfzz8n9kllzjw5y9y485xguawkw0clqh3k5s4a06jya2esejuxjatccf4jznf55f4xjvwjj52gg38l3ksa8jfp3mvxqy0324nkaslnm96k56ve0ekjung42jpwjmuhmrnq22ynmq8ffk2wv5rd5578gvtt09hqr0x9h0lznjy5s6p6q9xqfhpc05g5h9k63grec3amvny6y8jjkpfqgpuhxk24ejs93ech3s5ycqj3w3djs52x2pksu9lvczz66z49vruu2uus4tapncmkxm4p905j7qr2xq62z8df6vhf3ugxcekngqvc6g0y958s3vnzs9w6vaj0v4vddke4thuwr5rc033r7v8tgjg6jw6u3e7kqyfjqjnkdy5x3z9ww5d399fw6sjs5sf23lty4x6a6v9nyt4043yq6fprajg9rtu77x2qth6stfl896va5p59hcguv5079pmlgc25a8zuwrzhjvvxvarc5qjcgt7fa8h6aacr7jax529f68gv2vm37ejphlssxe928rkuezdzur7pzpem6e2jrrdqrvnq39mwd85lm5ncgkxdaz0d67mcza9msmerv8jfcs88y7w48zk4k9wutsasgfekdkjq9r23xgczgplvfga9hxzxm2z6xvmjmp7hquc95gmckpv5vzvux7hxjws2tl8z2vgm6vckhvq8rfljc9f0qdq6wy2w8sxl3mp25g5sd3h9afaa5ggd7g98wkryqh537a0faa359mh722seg6f0ssqwzm7y49vjvjra46yjc3zwqzp0ygc3gtnrrhs9yesm56frevzprd3yytqm4thv3fhdmexgv465a950xvlptk4s0hte6wzzskyj3scdtf0qjkjv25tn5ggc85wfadngz6jpjhjgm5c44ad3uqhgancst7f5dhw7dt5qs0q5p0ffaaejj9pv99fqegrypejzuuffhajpprtm9frx795umkwd2rgzhyxwnrez2z8yyvcctgenslapqq9uyzjk2t3hus43sfpxcg8fakques9kpy4v5pck4t2ajn8gtph3pquva984pqjq7mwxzh3sth5qdc722g5zztsxc90qy8sf4844p2k84kjv7jczymzhxvf2aqpfm2jgyze2qk8euzkx9l553nfaayue5el3dhyus8gu2cjfme4jzknl6p9zshr2cg4wfpz45t3xr2qh4tqplcvgqh0shye9rza2rek4j2ashjrrf4f8k7p2d32u6tq7v38j9jzn2lqw05m0q746q23kfvl2mxsyqant2uhg0fhzngete8kjcc0ughw7hluzklsqxwz3f5m9qvy9qrdfrmq22s7n4wqvrts3wtzhxpe09ngzlc76qmam7jlkrx59834ngt5w2j4wjk85wvrjrnzzra4nf2m2hdv8nswvhf39lr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T07:12:03Z"
  mac: ENC[AES256_GCM,data:JSB96ZMb8iPWoQIvy3SKB+3WMPWUkouFrv9PnKVThM9GKjlScVtTvG7pWgshpz2KQC1t4YXbV+9dITPlpsa04Qu1G170Ejk4AjYFlFrnYzXUIxszgTOSSN7QlqTTsoSrlXWNpl3HTZmVn3KvLIvvafXBKPpFc9DWKERm442A/N8=,iv:BPddbn5ykW0fDJn6WbTCW0gwF2pyJAeZzkg0SCdytBU=,tag:jvqMfIXMPfl7qyJ+6TeISw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
