# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:NdDt6LXp/saUJfWMYcff2TruFXIVjTZS35ETdsZGHWbBWgo16nn/9Q==,iv:z/aBvCW6JRG/Z9eKDdhYFtWjz41sL09awHiGIG2uzdQ=,tag:d1ZdBVqdKAuuwNfU2BiAwA==,type:str]
sops:
  age:
    - recipient: age17kkjwh97ech8ky6sa05xnyuxr9gpqwdjq8wjqc55a2mu7mdv9s8qvdfxpv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MGhkUy9wM1ZaUnlwWTJI
        ZzBqV0RkN1ZpNnJIM0crUnF6TGcxckUwVUV3CjVyUkF0YVlWcDVhNFRyU1hIbHpa
        ZkdSMmVxSDc0V3NqK0tiRlJHUll0SVkKLS0tIDhid01sc1RJV1M0N1BlVE9HK0VC
        MzFIeTVJUHMvWUJXMlA5aGpodklDNGcK15nxAXYbWiiB0jJ/bMYxo7Cq05FzMBVI
        icW7HEhtWYho0DM3iUxwYImcQSjTzCO23Ecx1nC1BOjcqhzzb6X6hw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-02T07:03:07Z"
  mac: ENC[AES256_GCM,data:9wFS2vNr4Z4Up5Co8Q1BmmJLL8Y8AqZW3gAqLQRP3DF/IjIuR19zv/iGrFMtHELzJrbethJ43JwYwWd5uTgbNBtDSFmfbVn7b7/4D0kxbmUPfvrm8RNu0jhhAIE3OReYq69jSp0ihhWF5+C5Th6FTzrtGlsDcKZlcHA8HlqRQIU=,iv:p5y9gz+8+FpU4QdvLgIuMGrqGEWXwu3yDYSjCS0jC/k=,tag:iCu2ItFJszF1adDmeXQqrg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
