apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:4Cmq/ui+emPQ,iv:V0gYS1UXBokGE2AAgeyEoRM8To1aAzCXz9hTsJcqkx8=,tag:qnxREfBUQBHl05Sfth988g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHZ3SEkycGsx
        aEkvTXRBNm5IaUp4aC92WVM1Q2YyMXVUUGt3WU9rejk0VU5OR0xQVmNNYjVvOHdu
        cHF2MFhmRUpJc1QxR3BONjBaRUpXNzQ5b3Uzb2Fmd0FkYkpobWdzUDBWVkRtVjdH
        b0RaT082Ryt5bTlTWnJ1di9UeTJ5MVgxNkFoWmRCeEc5Ui91QWdqNUJmR2ZCUmds
        eWI4YTBHTW9wOW92QVZaZXk5VDd6NkhteHViSWtwcUJ2TlplZ1cvbnlaTzA2RUJa
        RlRXSmJMNkgyek5wcHZUOVVEcXZTOWpPSTNkSEwyUUc3alVNMVNQM2l4dUdDV0x6
        MGhhTVBBSk9qS0k0NlRJSktBZnp5UzY3Q2Ywd0JMY2xQVXRhcTVIY0F5MGtybGVu
        cVNYb2dIdS9kV2gxeVhsdklhWjNyaW05eFR6NnNZK0pBUnpEdkNuZUtuUC9qdFpl
        cFFYamZsbnJUTHpqWUFVaTJpRmFwaUw5S2U5WTc5azMzbmNVY29HSFVVZzROQ2tm
        YzJmbnVFQTFubmpMRXh3R1NmK0xTVzlVWnRNdkhOaDV5N05OU3lVaXlvTjVRUld0
        YnM4d3RpakVKQjhUZy9vWjRFMUJrT1VldkJSUmljSmU0WkpPZExsc3pSQTRhYmhB
        b2VmQStZd0JiNVlDbTlXM1N5QWdrVG91S1lJWkthdU5Ta1JoT2U4SGEwdlY1TnYy
        b0xqWHlhY0pxdVdZM0ExQ00vajNCRWFBQVNVb3ByK2tYZGVMOWdWY25TRXpYWFVL
        TlVpTjRrTlZBZERuNEhxUWZNUVNTQmthR0VEZHlHakkrb0l6akNrVll5dkt1R0JH
        anJXZ2lvRVZOZVNhNlI4V2pkZnRFUjg2QVhWZVVRbzQwVGxFS2pDSU04QTFrWWFo
        ZUpoWEFlU1RacGxUU0NHT3FyUm5kS2ExTkVuQzN4MExiYStRM0MxSUtoMGFNQjdO
        b2V6anl1RFdCNEtSV0J5Tk5PVlRnSHZOdGxyRVN1cnJiM1I3L21YTjVCUXZtM2Jn
        SVlKaDAzQVZ0TTM4d2FJR2lUVlJoUVVGb0hoUUVKUmlMQXQ0a0pHT1R2VFVobHlF
        dEthRE5YS3dGYzhyYmJ3MDBNY3ZZU0Q0UE5DRnRleFJTR1BQOXlEU3Z2U3cvR1l3
        NGlXMFlNTG0vejNkTkpzZkEydFNGTHFEczlFTWw4Q2ZPaWh2a1FtcWF0UFRLUW1T
        amovZjF0Y21wdGR2enF3dHdUbmNLV0cremNiRFN6VWtldG9EMzBmanZoQStYOU92
        MjNOYk8rUkNneU5oQms0SjBPUHRZeVl0UUNVMm1ScGRuMEZ1Q2FqdWdVekVRSFBs
        aVNaQ3pTamZPSmZYdDIxVVQyTWlVUTlVNXBtZ3RFL1g1cUtGdUxsYW05a2lDQmxN
        cnptV3dEclFGSnVNcy9tMGRmRk0zRUxZUWg2NGZRajdtdVpySDhKSGcyZHAyeEJl
        SVdGZUdoWGp5RDdiYkVCeWdteExIajJWSE1DZ1YwclhIcG1SbjI4L0gveHNRb3pq
        dWRyVjdnU2lhTGVLQlN5bE9QZW9FQ01UVlo0d3AwajhMSGhIN3RHOWFFa1NmYkp2
        RWxZUWxJaDBtalFPR214ZHJkZVA5cExYdk5vaHFJdWg3RFdIcmJlVHF4cytYSGRn
        SWpTUXFBVUNNaTNwQkM4dVdLNmtiQ293QlYra2NYMGhjN0lzclB4RmVoN05rekU0
        MEZRQmdFZlozNm9VTEZzMlpndkc1MTB2eFpLejRKZmwwMVBDSVVWOGY2bS9YdThq
        ZUxMZUNRbjZKK0pWbTIzVVloNENQOEhHWGd1R0NQQ2JlQm0wczlROHRjOU55Njds
        Rm9zQm5aZVc3SEQ3Y0RLQlFLVDZOWTVqQkduTTlFeXNadkZselZ3K21QZ0NvelVX
        WkZ3TTNJOEE4V3g1QjdQVGxwWUtId2JIalg2QTRuWlJZNXUzdWRoK0RFWXlNZwpj
        djEvSGt1NDlGTDdtNCsvcVd2TEJqNWtieHNsL3EvNk9KclFYOUtkSTFNCi0tLSBJ
        a0dPSjR2ZU1sd0tNVWZRcUtqUHBpRUd2T3VyR0k2RER3K3pkd1h5dzk0CgUpBPj4
        nXg8xGrwDFkcr9U+eheTDwIPtYlUst+6yhDVeeTbV50RaXP+hqfZ0mo8AjqP3WhW
        zkmEXR5+5ErVdYw=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14wqvmn43wc3tquc22uyme4sgy0kyswdzcqlqj5xax2ftqsdwfs24s8a48f8nc0k6xp8a844zq3x20sj3p5q4htg203sy0am3ccng7369nm0mfjqt5lp9f2grzjsev7ktyl0zj9puz260864l0kktswsgwrwr8jyw2jurxjs2f7ys8mpg8urxfjfw5wggyeskg5j34x32hhtnk2kpugj4k3vx07s3a7desr08rn46jk03mc4qhkdq76sf0jgy02m76uz9l5y7rjd34y4vy5znya3j5q8q74sq2pqffy7uxcxrctuzgywvwdwptwq9yehchmhskgt56yfhedgae0nt489n3ld824tf73efvsgset2kkdneqtaaqs5t2zzk072jal2eg60n3e7adrjwgkvpdr99jleckkm48g7urry8v35s47v32a5qa75yk486sz650vxnany0jxjrl69kzsx38d4sg8ph4ccsf5f3sqexqm7fds55ckk7s958v2uhcwcqguve2f2k82g5yfzz8n9kllzjw5y9y485xguawkw0clqh3k5s4a06jya2esejuxjatccf4jznf55f4xjvwjj52gg38l3ksa8jfp3mvxqy0324nkaslnm96k56ve0ekjung42jpwjmuhmrnq22ynmq8ffk2wv5rd5578gvtt09hqr0x9h0lznjy5s6p6q9xqfhpc05g5h9k63grec3amvny6y8jjkpfqgpuhxk24ejs93ech3s5ycqj3w3djs52x2pksu9lvczz66z49vruu2uus4tapncmkxm4p905j7qr2xq62z8df6vhf3ugxcekngqvc6g0y958s3vnzs9w6vaj0v4vddke4thuwr5rc033r7v8tgjg6jw6u3e7kqyfjqjnkdy5x3z9ww5d399fw6sjs5sf23lty4x6a6v9nyt4043yq6fprajg9rtu77x2qth6stfl896va5p59hcguv5079pmlgc25a8zuwrzhjvvxvarc5qjcgt7fa8h6aacr7jax529f68gv2vm37ejphlssxe928rkuezdzur7pzpem6e2jrrdqrvnq39mwd85lm5ncgkxdaz0d67mcza9msmerv8jfcs88y7w48zk4k9wutsasgfekdkjq9r23xgczgplvfga9hxzxm2z6xvmjmp7hquc95gmckpv5vzvux7hxjws2tl8z2vgm6vckhvq8rfljc9f0qdq6wy2w8sxl3mp25g5sd3h9afaa5ggd7g98wkryqh537a0faa359mh722seg6f0ssqwzm7y49vjvjra46yjc3zwqzp0ygc3gtnrrhs9yesm56frevzprd3yytqm4thv3fhdmexgv465a950xvlptk4s0hte6wzzskyj3scdtf0qjkjv25tn5ggc85wfadngz6jpjhjgm5c44ad3uqhgancst7f5dhw7dt5qs0q5p0ffaaejj9pv99fqegrypejzuuffhajpprtm9frx795umkwd2rgzhyxwnrez2z8yyvcctgenslapqq9uyzjk2t3hus43sfpxcg8fakques9kpy4v5pck4t2ajn8gtph3pquva984pqjq7mwxzh3sth5qdc722g5zztsxc90qy8sf4844p2k84kjv7jczymzhxvf2aqpfm2jgyze2qk8euzkx9l553nfaayue5el3dhyus8gu2cjfme4jzknl6p9zshr2cg4wfpz45t3xr2qh4tqplcvgqh0shye9rza2rek4j2ashjrrf4f8k7p2d32u6tq7v38j9jzn2lqw05m0q746q23kfvl2mxsyqant2uhg0fhzngete8kjcc0ughw7hluzklsqxwz3f5m9qvy9qrdfrmq22s7n4wqvrts3wtzhxpe09ngzlc76qmam7jlkrx59834ngt5w2j4wjk85wvrjrnzzra4nf2m2hdv8nswvhf39lr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T07:12:03Z"
  mac: ENC[AES256_GCM,data:FyFgHI4GmTUA2kZ319OTjpOEohB/jpCywNyVZj1ET9IyrF/AVKMaSX8nV1otzH0dubZdGHrhFJSrTe+B/aJgOnAp0X17lhGuxCqR69EL38WlLjg7tognCHZ8FIyGHJrnXp2NLmocH1K/VzC7kKbzpwtWjGn9QQO7jj+ZWW01Iwo=,iv:+mxaB6qXfT/raidenwCI0eRbioYpx34OK/uDaYvcWCk=,tag:psuuTlbKei8vTcNsIgfisw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
