---
# yaml-language-server: $schema=https://schemas.gallay.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tankstat-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secret-manager
  target:
    name: tankstat-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        clientId: "{{ .clientId }}"
        clientSecret: "{{ .clientSecret }}"
        Auth__AdminEmails__0: '{{ $v := fromJson (.adminEmails | toJson) }}{{ if kindIs "string" $v }}{{ if hasPrefix (trim $v) "[" }}{{ index (fromJson (trim $v)) 0 }}{{ else }}{{ trim $v }}{{ end }}{{ else }}{{ index $v 0 }}{{ end }}'
  dataFrom:
    - extract:
        key: tankstat-secrets
