---
# yaml-language-server: $schema=https://schemas.gallay.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tankstat-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secret-manager
  target:
    name: tankstat-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        clientId: "{{ .clientId }}"
        clientSecret: "{{ .clientSecret }}"
        Auth__AdminEmails__0: "{{ .adminEmail0 }}"
  data:
    - secretKey: adminEmail0
      remoteRef:
        key: tankstat-secrets
        property: adminEmails.0
  dataFrom:
    - extract:
        key: tankstat-secrets
