# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:FVSN0TSPXy14RPzRJ+ewqVJuj08/yM/rBlSDPluj4QA=,iv:LNOD1XgXZ/1mST5W+NVKBgNYNToezTbooY8c6W2hfQg=,tag:2/ZCnBT7q6TAO24W2tqX0w==,type:str]
sops:
  age:
    - recipient: age17kkjwh97ech8ky6sa05xnyuxr9gpqwdjq8wjqc55a2mu7mdv9s8qvdfxpv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTnRXdkVEbkJzUG9zUDJs
        dU42VWY3R0hmajIwTkpuV0toVVo3TmxaUHhzCndaUkhQVFpOVWdyTmpuY2x4aDNI
        bVZEczJxd3RpQy90TTJSTEd1cytzdXcKLS0tIEJkU2QzaVpGNGpsWER0VTBhM1Fv
        aUNiUFY2UzhyZ3VWSmN2ck1xZUowTmcKXmxlzNxgc7YYKx1/ImLdxlfN8nSnhctm
        nCYU5zdk7xoJgQjPjoZ+88kBI2Jrh1raa4+fkwrNTjwIdfYGbshl1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-02T06:59:26Z"
  mac: ENC[AES256_GCM,data:w+Wn//C1RlwtowI5bCikby1svF5d0KfiB3GITQW1vPSAOeNRUUxROLYtbvNKqWC+W0vA1L3L5ax/wswhxt/Qezgos9kcMrNS50lpk+5iR+iRK96cqReXFMsxy/5pgiygpkYgkT3J2P6usd4blYwdJOBBqcaUKZk+Kgxmw5sOHNk=,iv:i+sGoF4GVtgcv9xTW7rt7FajFQbwdnvLBT0UPSHeoW8=,tag:tkIixKU1Rlv8pLSXdPlcxA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
