apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:S1ukoWPE3NI6EBjCfKSgUBY+wTaygexWPh3dRLvhlAg=,iv:E9rof5RVRStgIKttt8VedbEeuqpdTndyaENe4x0HYAs=,tag:wzx9WdERc1/9ecxu9HLisA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEYzaldQWE1X
        V2x4dzF6TmRPZ1J2VjZ6c2YwZEsxN2V5blZURUxTMlViMU9mV1ZFRHU4RldFT1lk
        WjZVVTRSU21YRFF6d3FCRXJTMHpFQ0FMTW42bUJKZEhzbzNqdzRabnNxZ2YxcVBn
        VjM3NDlUUDg3bGpoVUUwaGlGQ0dxcFJyakNxaTRjeGNTa3c0Z0ZTRng2ak5COVNh
        OXFrWTM4UjJ6dXRlZU9UYnZ5RTVRL2FuWENSVlVJR3B0UGdjWXkwL0pFcWpMWkta
        TGxkZGNhRWsrcE9VY21UV3NaeU5WVzl1a2h2RStwNDJHZUJadEdxRHExL0VwTmNa
        UklzZGFVeWg5TjY4N1RSQmFiL2RYZzlFQ29MbkI4Z20zWHVsd1JjZU1GamlkS0tp
        cm1LTUw3TDArTll1bVFyY0tjTzIzR252cUdoKytrV3Zqczl0TklDYXEwS3lXZXMx
        dXZLYVgxVGlCWjZqRmxYeFNkOHNHRHJWcDlVeWUzK1hJaWJuNnRJakFUNUhVWjdN
        WjBKdlNWVW41L3NHUS9HVm1HSFVxaXdXUzhLZXlOd2RweThYQVFWMVpaMktES1Qy
        MmhYd2Erc1o4YXU2NnpYeVpoeFdKc3Ixb0grbGVNNjVGak93YndvNzdWZ2pWYVJn
        MDh3cXBtM0d5QTk4aFV4MXpKbm5nL25kSmhRYjE1VmoyRVhkeHZzTzBtUkg4WmpN
        Y0hlWkwvM2lHaXBMRGFsWERnTEI3bXU2Nm5MbjV4Y1RzbUU3QzZobUdjc1pNcWp3
        b0RCTFYrbGdPMnNXNm0xME9SM2xPdjVTZXRENEVHSk5aQWppUzRBRmpOS3lPeDlO
        R1VtQnJGSHVqRkpJei9aVTRlbHo3WCt5RVlEbzN3QTdlVmcvUlVFL052V09Ycjhp
        LzlwbWJreExIRmVtWDdGY2pPdGl0UEdUTEZlUlBwY1U3eE5SNXdoUjV5SjV0YzlU
        Ti9JZWhnUWxlN2JoSlN6NjIvQ0h4VGorRUVTWjdseGZhdFlsRUhBSFAxTjRqbkNS
        czc4V1dqckNxbFJDZ2ZhcEEyanVmNStkY096QXFFVFc5bzdnN1NjbWw5emlzTm96
        VWFDRWdHZnRGanc1TDRBNzJBc0VNc0NFdEtvaDBjVVc1ajB1V3BDTVRtdW55Vy9w
        QmJ3OTFmYnpwSTdodnc3R25jOWJSRC95UE94eGRhWUR2VFdoZUovUUtQK0dyYllQ
        YXFKZlgraityWE5RKzB2cmh0OEZmNmlrZU1hM2F4K3RKTE5ab0plcU8vNFNtazFn
        SHJ2M1JqMk00TDExai8yWjRUT2JNbU5Ud3RndEE4K2FjU0QxTk4yR213TmpIUkxo
        KytFNmpUWGxzcmx4T0pZYjZDa1YxNTNmTld2L0E5MDMxUmhMcSszaEZwcndocFNm
        YnFqVXhXdGk3SnhVQzQwSTdFMzZURkJZeDhEZFI2eUV4Vmd0WldYblN5MXFudHZJ
        YzdxVnNWNDAwZmFsUjZSN3dOSDJpZHM5OXRCRFlHOTU2TEU3RmoxclJPaXVMWHRo
        TDlBbTFhaXBLRE12OGR6c28vZmdGdnlxdUtUU1Q4d0JPbnpkTStwTjBheU4wd0pJ
        QVpycFRjd3BLSmVWTWwvVDhmaFNrTVFkQThBQ3ZYcEFyNTliMU5RcFk4bmhNbVhs
        VkdaN2UwVzE5Z2Z5QmFVKzIyYmxoQWRnYUVlb3BvQkpoUmtRU3ZZbWlqdi9qZkJK
        MmFZN1pnK2NGaTZ6NVVyUUs4bnZUQmc2MDBtZW9wa01lRjBwWDdrLy9STGRKbEpM
        K2ZLem13aml1K0RxQVpiTDFKQnBJcEQzSDNuRzNyc3poOUF5TkxRcERzQmsvL1ZK
        MkpMZkVUWUVBZnhoc1NvSUs2TlpCbTZwQzE3OUR3ZzFuR1FQUHNRLytVYlp2eE1D
        T08rTVplUExRc2Z2Wnk4TUl0UHBGZUw0STZtZ2FjTEJZSUoxTE1SV2xhRElkQQpn
        d1AwbE1RaWJtckMrODdZTWhRMkh2OHNYcHFqY1Z6VHZlME9FRTFuZzNzCi0tLSBM
        VHcxYk5NNDA5N2RLU1NxZExHYlZVWlVGRTh4YnRaWXZobUN3bWRzam53CuA6EU4m
        b2Fyyo3LLyIsrTnq3BijMzkg6/OfbbaF93lHIKA/L1t8JuVZRVOG7cGPbiJTManH
        610nypQQ5rdhADY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14wqvmn43wc3tquc22uyme4sgy0kyswdzcqlqj5xax2ftqsdwfs24s8a48f8nc0k6xp8a844zq3x20sj3p5q4htg203sy0am3ccng7369nm0mfjqt5lp9f2grzjsev7ktyl0zj9puz260864l0kktswsgwrwr8jyw2jurxjs2f7ys8mpg8urxfjfw5wggyeskg5j34x32hhtnk2kpugj4k3vx07s3a7desr08rn46jk03mc4qhkdq76sf0jgy02m76uz9l5y7rjd34y4vy5znya3j5q8q74sq2pqffy7uxcxrctuzgywvwdwptwq9yehchmhskgt56yfhedgae0nt489n3ld824tf73efvsgset2kkdneqtaaqs5t2zzk072jal2eg60n3e7adrjwgkvpdr99jleckkm48g7urry8v35s47v32a5qa75yk486sz650vxnany0jxjrl69kzsx38d4sg8ph4ccsf5f3sqexqm7fds55ckk7s958v2uhcwcqguve2f2k82g5yfzz8n9kllzjw5y9y485xguawkw0clqh3k5s4a06jya2esejuxjatccf4jznf55f4xjvwjj52gg38l3ksa8jfp3mvxqy0324nkaslnm96k56ve0ekjung42jpwjmuhmrnq22ynmq8ffk2wv5rd5578gvtt09hqr0x9h0lznjy5s6p6q9xqfhpc05g5h9k63grec3amvny6y8jjkpfqgpuhxk24ejs93ech3s5ycqj3w3djs52x2pksu9lvczz66z49vruu2uus4tapncmkxm4p905j7qr2xq62z8df6vhf3ugxcekngqvc6g0y958s3vnzs9w6vaj0v4vddke4thuwr5rc033r7v8tgjg6jw6u3e7kqyfjqjnkdy5x3z9ww5d399fw6sjs5sf23lty4x6a6v9nyt4043yq6fprajg9rtu77x2qth6stfl896va5p59hcguv5079pmlgc25a8zuwrzhjvvxvarc5qjcgt7fa8h6aacr7jax529f68gv2vm37ejphlssxe928rkuezdzur7pzpem6e2jrrdqrvnq39mwd85lm5ncgkxdaz0d67mcza9msmerv8jfcs88y7w48zk4k9wutsasgfekdkjq9r23xgczgplvfga9hxzxm2z6xvmjmp7hquc95gmckpv5vzvux7hxjws2tl8z2vgm6vckhvq8rfljc9f0qdq6wy2w8sxl3mp25g5sd3h9afaa5ggd7g98wkryqh537a0faa359mh722seg6f0ssqwzm7y49vjvjra46yjc3zwqzp0ygc3gtnrrhs9yesm56frevzprd3yytqm4thv3fhdmexgv465a950xvlptk4s0hte6wzzskyj3scdtf0qjkjv25tn5ggc85wfadngz6jpjhjgm5c44ad3uqhgancst7f5dhw7dt5qs0q5p0ffaaejj9pv99fqegrypejzuuffhajpprtm9frx795umkwd2rgzhyxwnrez2z8yyvcctgenslapqq9uyzjk2t3hus43sfpxcg8fakques9kpy4v5pck4t2ajn8gtph3pquva984pqjq7mwxzh3sth5qdc722g5zztsxc90qy8sf4844p2k84kjv7jczymzhxvf2aqpfm2jgyze2qk8euzkx9l553nfaayue5el3dhyus8gu2cjfme4jzknl6p9zshr2cg4wfpz45t3xr2qh4tqplcvgqh0shye9rza2rek4j2ashjrrf4f8k7p2d32u6tq7v38j9jzn2lqw05m0q746q23kfvl2mxsyqant2uhg0fhzngete8kjcc0ughw7hluzklsqxwz3f5m9qvy9qrdfrmq22s7n4wqvrts3wtzhxpe09ngzlc76qmam7jlkrx59834ngt5w2j4wjk85wvrjrnzzra4nf2m2hdv8nswvhf39lr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T07:18:43Z"
  mac: ENC[AES256_GCM,data:1oz2RZwqZiIPWQt2S17fuOymhiiCsUGhoXalU98YJHWwFHdP6qeNq7XWpZS0Z19r68RIMnI26mJsmDuHRI3rCgYoGvImEd9H+xCZaiEboSU8Op0+sEcpONkSEjPy4Y4Cs1LScW6VnSkc0vxGy+QSNCNN8KBU8m0Fd0U8mDnZ9eM=,iv:W0TiP8eg0u123q9WofPOuOEE2yvKr9eT4JzP4jakUdo=,tag:lLuBLIQ4D2AShC29jdIjXQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
