apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:f/gCD0bZN7UqzO+KTPEcYNYW/P7uUkOWf9Ju3mMge9U=,iv:apyUwvzSPGfc1hwVBMQU+ZnfiCmTYjGCR0Or50qKlRI=,tag:tOGr3PRgYNQ8yzvhGLakfA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHpKY0ozZFUv
        RUpicjJLOElJT3JickVQNkJxbitSZ3E5b0o5QmphL3ZSMTFvTGJuL3hERThVZHEv
        QTI0TjdGNWFDcGRxUkhHaWpYeHk1OFYyMmNzZFJxV2dCdlZBNGt5SUxzYW5EMnk2
        eDJ6Rk14RWQ2ZytlMk8yVFFLZW03K1NYRHl2ZTFrUFRKNHB6VUg1NHpjQmN3Z3JZ
        a0Jua0pVeWFmMDFWZFNlazI0RlRLeis0WWVJaDdWUzJJclVMUmk0SnNhdlhKcHRQ
        VCtQbVBDZDJRREx6elFFVVEvSGpUdXVNbXpiWTlVVjlWZWsrejFVTFQwcFdHS2la
        ZUtsaFpXV1J0K1dQNW5GMmlvSlN0Nng1WnoxLzdFaWJQTk9JZUl6cmR3SU1kZHVU
        Nko5RVI0ZHRoNzA2M2xBMlhBMVNRV1gyWVJZTEFtSlVEMFoyU3hld05aOXlqbmhN
        VEw5cjA3bVluSVNocUc4cGV1eGlMSlNNZ1RSVk1sR0hXUm5lMytKMnJQT0UwS0Jm
        T2FML3pUK0VnTUl4SlZkRll0L0JDM05HYTlhTUdtakFWUTVHU1lQVW04bHFNcExO
        cWxnNk1Cc050cm4ydXhHUkFMald1aFhtVnlOOXJCZzYvMXcrYytjUExZTDRaNytF
        OWJkOXNSL2szaEFPNjFSTmpkaG5iVStPQUt5OU9xSWFGNldKVTExRytMeDJ5WEFi
        VTZCNkZ1aCtwcXBrbnhNMDN5K0pNV2wxK0g1aTVTaGRQWG5jeHpuaWc2Znh5SlFY
        N2tya1FNaWpQQlRDNFByaEZzUmtucWFtVDVDSWlwS1Q3VEVPNldnWXo5VmpaWnNh
        WkJxSFE5RUg0dU1xeWJXUzREM2lhelpteUdCRHJtZDcxbmdzY00rblF4cVREQlIx
        MFhkcmNWblVPU0JVVGk5cUJGN2RyQUlrQzRnVzMxRklFVjJ0aEhxQmhSUXQ4L3l0
        QjVqZVdiL1VNRHgrSTg4enY2WkZQWnJGS3FUd01IVXlSWWE5Z0pFSmtIVEJjQ0JE
        bTl3QlliR3ArQ3FoN0w2Mlp3ZDNEdDRHdmJlWTlKZjc3NEczYUhOdkMyWlZzVjBD
        N2hFRmE5Y3J3WGJxcGJ5bDRFRUNZbmlRL0FIWHkxcDB2T21QYmphUUdkYjg0VWxD
        U005WTVFRFJUZ1phbE9SZEpSYTBBMjhJRGJFazBCY05pdU9HS2dFbTlVQ21Dd0px
        YmlvUFJiUnY2U3g0QmxMdWE4UXQ4bm50b05nWUpocHlNQlB3SlFkYmd6dktnNUlD
        OUN0bWFjei9sNWRsMnRkOFhSZHFlOXBIZXFqYi9lbjBIKzZaMW1TdXhYc04vakIr
        dlA0Ui9PZnk4eXptVDMxSW1pb01NaWhqYlA2NnNpRHhYaFJYUHJiSGhRcVVpV2Ix
        S1Y1T1kybElpdEo5Ny9RTEp6b2dWa3hLUXY4eVczVUNZdHFmRHZhNjVoTTFHbUJT
        Vkw4NjQ4WFVuRzF6N1RndHNVMllBbE4rSWNWd1p5NjlDN21waklvZ2g1NFhkQng2
        SzdOZzJNU3dMdUlXT2pveTVCV0pGQmc2N2tPU01UZlg3Z1NhejFPWTlmZlNTaFFw
        c3dFMktFU01qSWQ0YkQxUWxjcWVSNXYwMzZxWk96TlF3Y095RFR1MEx4QXFlOVRo
        Vk4vYVdPeTF1NjVLV2xPVTZoeStHZXdEWWwveWpJa1VqZnQwSTg4eFdYWFJYOGNG
        djJJRk96NEhWSFlTUzN6dHZGMjZCR0NYaXFWMUlTbzV2Vm1iNnBjVmFlcjNjQmtu
        SVJqcUZISVNjR25mZFVMUnl3NTdUdTI0MVJPYTZsVXlyZDVSdkpuNW05UG9lNlpz
        VDRyTSs0bnZPUE5VUkNLa1hjd3lsWXRrTFQ3eWJPMFprb2JZNDIrbUFXTW1xYy80
        clZiU3hqaWJPNmcxdW15cHdSU2tTZGwxQzQ3czJHUTIvVG8wL0VMYTdIdlJjUQo1
        OWMrYks3WjBsUzl2aUxNMzIybG4zTFU2aWpoS1dwcEd5a1poRGdHd0dZCi0tLSBs
        WXZZMVYyb1ZsSlNZaEM0NWsyMURzUXVHeGJrSmRqSDVKdzNYK1AwNWhvCqq4i+js
        wGKvg+aWYjY7pv0MgxbFRBhX0Y5aRr2sJD+NayIc/qtYWz2g9kQvwjnRF3IhG4wI
        hEmGmf4PFbqIK+Q=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14wqvmn43wc3tquc22uyme4sgy0kyswdzcqlqj5xax2ftqsdwfs24s8a48f8nc0k6xp8a844zq3x20sj3p5q4htg203sy0am3ccng7369nm0mfjqt5lp9f2grzjsev7ktyl0zj9puz260864l0kktswsgwrwr8jyw2jurxjs2f7ys8mpg8urxfjfw5wggyeskg5j34x32hhtnk2kpugj4k3vx07s3a7desr08rn46jk03mc4qhkdq76sf0jgy02m76uz9l5y7rjd34y4vy5znya3j5q8q74sq2pqffy7uxcxrctuzgywvwdwptwq9yehchmhskgt56yfhedgae0nt489n3ld824tf73efvsgset2kkdneqtaaqs5t2zzk072jal2eg60n3e7adrjwgkvpdr99jleckkm48g7urry8v35s47v32a5qa75yk486sz650vxnany0jxjrl69kzsx38d4sg8ph4ccsf5f3sqexqm7fds55ckk7s958v2uhcwcqguve2f2k82g5yfzz8n9kllzjw5y9y485xguawkw0clqh3k5s4a06jya2esejuxjatccf4jznf55f4xjvwjj52gg38l3ksa8jfp3mvxqy0324nkaslnm96k56ve0ekjung42jpwjmuhmrnq22ynmq8ffk2wv5rd5578gvtt09hqr0x9h0lznjy5s6p6q9xqfhpc05g5h9k63grec3amvny6y8jjkpfqgpuhxk24ejs93ech3s5ycqj3w3djs52x2pksu9lvczz66z49vruu2uus4tapncmkxm4p905j7qr2xq62z8df6vhf3ugxcekngqvc6g0y958s3vnzs9w6vaj0v4vddke4thuwr5rc033r7v8tgjg6jw6u3e7kqyfjqjnkdy5x3z9ww5d399fw6sjs5sf23lty4x6a6v9nyt4043yq6fprajg9rtu77x2qth6stfl896va5p59hcguv5079pmlgc25a8zuwrzhjvvxvarc5qjcgt7fa8h6aacr7jax529f68gv2vm37ejphlssxe928rkuezdzur7pzpem6e2jrrdqrvnq39mwd85lm5ncgkxdaz0d67mcza9msmerv8jfcs88y7w48zk4k9wutsasgfekdkjq9r23xgczgplvfga9hxzxm2z6xvmjmp7hquc95gmckpv5vzvux7hxjws2tl8z2vgm6vckhvq8rfljc9f0qdq6wy2w8sxl3mp25g5sd3h9afaa5ggd7g98wkryqh537a0faa359mh722seg6f0ssqwzm7y49vjvjra46yjc3zwqzp0ygc3gtnrrhs9yesm56frevzprd3yytqm4thv3fhdmexgv465a950xvlptk4s0hte6wzzskyj3scdtf0qjkjv25tn5ggc85wfadngz6jpjhjgm5c44ad3uqhgancst7f5dhw7dt5qs0q5p0ffaaejj9pv99fqegrypejzuuffhajpprtm9frx795umkwd2rgzhyxwnrez2z8yyvcctgenslapqq9uyzjk2t3hus43sfpxcg8fakques9kpy4v5pck4t2ajn8gtph3pquva984pqjq7mwxzh3sth5qdc722g5zztsxc90qy8sf4844p2k84kjv7jczymzhxvf2aqpfm2jgyze2qk8euzkx9l553nfaayue5el3dhyus8gu2cjfme4jzknl6p9zshr2cg4wfpz45t3xr2qh4tqplcvgqh0shye9rza2rek4j2ashjrrf4f8k7p2d32u6tq7v38j9jzn2lqw05m0q746q23kfvl2mxsyqant2uhg0fhzngete8kjcc0ughw7hluzklsqxwz3f5m9qvy9qrdfrmq22s7n4wqvrts3wtzhxpe09ngzlc76qmam7jlkrx59834ngt5w2j4wjk85wvrjrnzzra4nf2m2hdv8nswvhf39lr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T06:31:48Z"
  mac: ENC[AES256_GCM,data:MkchZEuVd6NqqAU23fY6JHKDJ892AcBCkduxnWdxpo5riIbumQDH79/Zfu5ekPnzrbdQmMF/ZcjiKJCBR2Pyuc/UOXWK4oB64C7m+hh8G5x17eD/s0jedl6W6xz3tDHcq0yzTrb78eBgLWYLDoI03ckGT3IqcM9kx+d9V++Qv/s=,iv:j5tOh7dPU4Mj6u36SjjfzQgCD8a0plf5xLBJ15rOa0E=,tag:2NazS2BEZuP2BBImFpWH3Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
