apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:rTkx2/CZh5JeodLBDuoYNITLP2w6rT1Tn6VFsqI5w4c=,iv:GZNKc3DCwX+VxM+SnAekfab/aYY5u9Qq30EoTnU2Ipo=,tag:wHrMsVW8HBK4gQYsJRlsew==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEZ3cm9VZlkr
        Q0k2eTlzNTJ1OXBvV0tTWG1FdmpwSExCNUxWZ2lMOXo0Y1pkaGhHUThSYTI3TVE2
        SE5JRXZuUFphRXV2S2s3QzFtdmpKTVlFZm4wd0dEODdsMEIwVU5ZRWVhNHJMTVBT
        Z0FGL0MwaVR1NllwUGZLS0tFU25ONHVnZ0RpOTlvMHdzZVBpbks0bzhpZytEbFMv
        OXVJTkFtTWlZTUdvemNXczZZSkFxUGZ1RGxrNEE5cmMxWmtldGRTOGs1dTU0TU9p
        TnhzUHAwSWN5TzdMTkdzQ3VOZG9CQ01Walg1ekplV3kyYUhBY1ZuejdjNks1MEFj
        anRVQ2pISmNqL2pTTHhlV1FjZnhwZkdjRXFGWXFyeUc3bVBBSzNBNUVGRHd5TFh3
        MHdxTEZpbDZmdk9kOU1lQjB4V2w0NURjYjY5QnYwRzVjclkzT0cyZ2FIRXhzK0xx
        UjZPV3QzSjh4YmN1UUlaTmZ1czBOVGNCMDRiZ3orV1R0MnhKS2o4UFRsZWVad3Vn
        RHFXeGpQMmlGZlZZTklwK09hVnV4UXNjNWw1UHpWSmFyL0JlVkJURXpZVEdvdytt
        NVRUVVVGVVliV3FiVjZDSFZ1UDYyTCtKUkZ0bzZubkNZK0dHNEFRVWY3bXVka0Rl
        bGROYUQzMGsyOWNzV1ZFTHR2SjdxRDZMVDVjMTZMTm1zMkg2TWdMMmFBUWladUNK
        OFdjcWhPaUZ1aHF3aURocXlyTkJKeGJVNFJva0pxQVh5WmlNTnVoWFA0NE5MN1d6
        VGxGRDJIVXdqTWJlR2g2Z0ZiRGtVSXMwOTZPd1Y4T3JFSHlnUk5JZ0xYWDBSK2Fl
        Qmx5M1g2Qm5Wc0grRmJLTXdBYk4rK2l6YU80MVRYMDlsQStXYzl6T1JVK096S1dt
        SWUyRUdDbnk2YkIyY3NObS9pSERTUGZPNDNxQ1FJYWxwOWRDdTFOWkc3WVBpLzdC
        MkR4b0kzZHZFSnM0bVplOWFDTE9ybUlnRlhuRFlVbjE5UVJLTmxBMWc0cE9XVHl6
        cHdFdFNrVitwTE8vOG85Z2NRTWl0bnhlTHNYQ3Q4Z1VBSWF1d3ZQUHdUUDNIVkNK
        THpIS0g0Z01Lb096Y3dXdnA0bnp3dG0wZ0x6L3Vrc25wUm5NZlVzcWFOeTBCdnRV
        YXU5cUZzMlhNd3FlaXZ6WDdzNDFFR2xvd3VERTF3U2xBMEptMzNZeGwwNzhWeUNr
        bzNyd3cydTBlWXNwQ0pHb0xGeHc0dVJ4blp0enI1bmYveVg5MU1CTkpCTW0yQVNX
        RS9mZURackl4aUpoL1BTcXNqRHBETkNydFBkUTRNMjZBWUd1eVh2QWJ4TlJ3d3dw
        WGh1QTVldHAxbDR5ZEVhS1pFMWtBVGdmWWdncjhxVUoxTHFIQVJWeEZJcVRRMEhU
        dEsrS1R5a0FkeTRGV3JsK0cvY2RDTlJtNGIreUJ2Qm9tQUtWZ29kbDRodE8xSlU2
        S2E2cjAySDQraWlVYzg1aVFYWTNGYjAwSks3RzRzb1N3S0JCZk4ySUVPV0l4SzRB
        TjBwYjRkWnVLQlIvakd4NTdyUkNtRzg3TWhabURieXlyZHZBcWNDRktxYTd2a0JW
        R0NxY3lrSW9BUEkraUV4VWdGcER1KzZKQWg1a2cxa3dVYlQ4SzB0TDRRWnZYLzdH
        aDRrVHVmd2VBTXNwb2dSdTYyaGdxcGZRZXR4QVZ3M1V6VWRGS29SNDdBaHBrT0xl
        NjBJbkJCZ0dSMTNuTXZFVTFpZDVNQ3BsOFBvYU9RM2gzT0prRHNYY08zNXMydG5L
        c2lEalllazRVL1lGY3poQStCeFZDS2xkVExlZTNlT3pDeUZTUCtJNkd5STFwRjMy
        RDlvbll5b2xZcHNoUGdxYnY1d25IU3pscUs5Y0IyNjlhVkU3cmxjU1RWTFVHYTU2
        SUEzcTV1Y3llZVNmNkQrN3hhNlVDdzVnLzFEYVRSOVFaTkFhVzZReGE2NGNEQQpR
        L0Ixek1vMWRDSlo1R2xMa2NJcXdjS3BsMXBwbVJleE9IYVp1U3ZNT3lVCi0tLSA3
        dDhSQWN3YUo0SE9TbE00bkFrN0JhWFdFZ3k2SEh0REJ5eWgyN2QxMENBCgkF02zH
        MFrR4pXtrzzdyHc2cMcpJ6VnVJY/Hj8etylxEm03CpTjlETTOSZBZRlR7W+oSW+R
        Uc/GGf0EwNLuXVo=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14wqvmn43wc3tquc22uyme4sgy0kyswdzcqlqj5xax2ftqsdwfs24s8a48f8nc0k6xp8a844zq3x20sj3p5q4htg203sy0am3ccng7369nm0mfjqt5lp9f2grzjsev7ktyl0zj9puz260864l0kktswsgwrwr8jyw2jurxjs2f7ys8mpg8urxfjfw5wggyeskg5j34x32hhtnk2kpugj4k3vx07s3a7desr08rn46jk03mc4qhkdq76sf0jgy02m76uz9l5y7rjd34y4vy5znya3j5q8q74sq2pqffy7uxcxrctuzgywvwdwptwq9yehchmhskgt56yfhedgae0nt489n3ld824tf73efvsgset2kkdneqtaaqs5t2zzk072jal2eg60n3e7adrjwgkvpdr99jleckkm48g7urry8v35s47v32a5qa75yk486sz650vxnany0jxjrl69kzsx38d4sg8ph4ccsf5f3sqexqm7fds55ckk7s958v2uhcwcqguve2f2k82g5yfzz8n9kllzjw5y9y485xguawkw0clqh3k5s4a06jya2esejuxjatccf4jznf55f4xjvwjj52gg38l3ksa8jfp3mvxqy0324nkaslnm96k56ve0ekjung42jpwjmuhmrnq22ynmq8ffk2wv5rd5578gvtt09hqr0x9h0lznjy5s6p6q9xqfhpc05g5h9k63grec3amvny6y8jjkpfqgpuhxk24ejs93ech3s5ycqj3w3djs52x2pksu9lvczz66z49vruu2uus4tapncmkxm4p905j7qr2xq62z8df6vhf3ugxcekngqvc6g0y958s3vnzs9w6vaj0v4vddke4thuwr5rc033r7v8tgjg6jw6u3e7kqyfjqjnkdy5x3z9ww5d399fw6sjs5sf23lty4x6a6v9nyt4043yq6fprajg9rtu77x2qth6stfl896va5p59hcguv5079pmlgc25a8zuwrzhjvvxvarc5qjcgt7fa8h6aacr7jax529f68gv2vm37ejphlssxe928rkuezdzur7pzpem6e2jrrdqrvnq39mwd85lm5ncgkxdaz0d67mcza9msmerv8jfcs88y7w48zk4k9wutsasgfekdkjq9r23xgczgplvfga9hxzxm2z6xvmjmp7hquc95gmckpv5vzvux7hxjws2tl8z2vgm6vckhvq8rfljc9f0qdq6wy2w8sxl3mp25g5sd3h9afaa5ggd7g98wkryqh537a0faa359mh722seg6f0ssqwzm7y49vjvjra46yjc3zwqzp0ygc3gtnrrhs9yesm56frevzprd3yytqm4thv3fhdmexgv465a950xvlptk4s0hte6wzzskyj3scdtf0qjkjv25tn5ggc85wfadngz6jpjhjgm5c44ad3uqhgancst7f5dhw7dt5qs0q5p0ffaaejj9pv99fqegrypejzuuffhajpprtm9frx795umkwd2rgzhyxwnrez2z8yyvcctgenslapqq9uyzjk2t3hus43sfpxcg8fakques9kpy4v5pck4t2ajn8gtph3pquva984pqjq7mwxzh3sth5qdc722g5zztsxc90qy8sf4844p2k84kjv7jczymzhxvf2aqpfm2jgyze2qk8euzkx9l553nfaayue5el3dhyus8gu2cjfme4jzknl6p9zshr2cg4wfpz45t3xr2qh4tqplcvgqh0shye9rza2rek4j2ashjrrf4f8k7p2d32u6tq7v38j9jzn2lqw05m0q746q23kfvl2mxsyqant2uhg0fhzngete8kjcc0ughw7hluzklsqxwz3f5m9qvy9qrdfrmq22s7n4wqvrts3wtzhxpe09ngzlc76qmam7jlkrx59834ngt5w2j4wjk85wvrjrnzzra4nf2m2hdv8nswvhf39lr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T07:12:03Z"
  mac: ENC[AES256_GCM,data:2SXm2Y41gfBU9x49VnLuyr2YFUxuweh0rXeuMKPVKsBa8p/dy415sUEL3hJTMWr//z5+lTepPf4+QTn5cndzjzLHchg5fn1v2ktZg0VO/WXncuiISM6/Vjw8yIAYo/XhiT+tY8WjMN75A+myCgKseq+KeRJrClAME5mApdhaCbM=,iv:tpq8gfRpXn/+PrWNHn9zZqS9oDzoPcqwbwItEYjb0Hk=,tag:wuP8VKyVRbUqX9xSSlrO2g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
