---
# yaml-language-server: $schema=https://schemas.gallay.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tankstat-env
spec:
  refreshInterval: 1m
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: tankstat-env
    template:
      engineVersion: v2
      data:
        Database__ConnectionString: "Host={{ .host }};Port={{ .port }};Database={{ .dbname }};Username={{ .username }};Password={{ .password }};SSL Mode=Require"
  data:
    - secretKey: host
      sourceRef:
        storeRef:
          name: tankstat-k8s-local-store
          kind: SecretStore
      remoteRef:
        key: tankstat-app
        property: host
    - secretKey: port
      sourceRef:
        storeRef:
          name: tankstat-k8s-local-store
          kind: SecretStore
      remoteRef:
        key: tankstat-app
        property: port
    - secretKey: dbname
      sourceRef:
        storeRef:
          name: tankstat-k8s-local-store
          kind: SecretStore
      remoteRef:
        key: tankstat-app
        property: dbname
    - secretKey: username
      sourceRef:
        storeRef:
          name: tankstat-k8s-local-store
          kind: SecretStore
      remoteRef:
        key: tankstat-app
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: tankstat-k8s-local-store
          kind: SecretStore
      remoteRef:
        key: tankstat-app
        property: password
