# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jitsi-admin-mariadb
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: jitsi-admin-mariadb
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: democratic-csi
      namespace: system
  values:
    auth:
      rootPassword: ${MARIADB_ROOT_PASSWORD}
    init:
      enable: true
      databases:
        - name: jitsi_admin
      users:
        - name: jitsi_admin
          password: ${MARIADB_PASSWORD}
          grants:
            - database: jitsi_admin
              privileges: ALL PRIVILEGES
    service:
      type: ClusterIP
    volumes:
      storageClass: iscsi
      data:
        enabled: true
        storage: 5Gi
