# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.35.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: jitsi-admin-database-secrets
stringData:
  MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:0lmOp6mWiyr02UmqIOSa1Ds40nY1kIuOxowok7dJYsk=,iv:CaTweA0oZnmiN5wA0tHuxCRy9tWW4DTwW2JhGhw2Z44=,tag:hHnjnxXhe1Oo0z+a1gX0Dg==,type:str]
  MARIADB_PASSWORD: ENC[AES256_GCM,data:dGbcoWDrsL1dzQLn5U5F4eljhJQA0pPQ2CZ1Yp1mGcU=,iv:ttNdB6AlkZzePzLsCuhYS6/1mpry3ZzAvMMLhdfMZHc=,tag:/cgnfrKtg/A+ghxei6zOfw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjM2tLQlN2WEVMV3lyZWtU
        Z2hQUlNRSktJSDNLbURhaVV3cCtEQWZrdkNNClFLanhJOHR6d1g1UGVDZkZORHJl
        cXczdVRNNXNOM0p6azV2ckJRNkNPQjAKLS0tIGtNaHFGMlhjSEllVVQ1UjNxK1RP
        a1NTaVFVS3YvbjZhaDhZUHk3SmEycmsK5xKjRm6kNDiCUUfiT3QILdNxApsFm+O9
        FX7q1b3PBIeOA5AaDMCtu6P7fdXneglGsY7wlc3Z0ZJFDzwsyTLmFQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17kkjwh97ech8ky6sa05xnyuxr9gpqwdjq8wjqc55a2mu7mdv9s8qvdfxpv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-14T18:25:54Z"
  mac: ENC[AES256_GCM,data:m/7PNs/fZXeOWKN0sfled1X9JC3bUOWSXiCLSOqlpsnu6sxiwjrZ8RYWCM+KxUVsz+JCLhCPTBlc5S4/r2vPROvf8vzYrbLcD2tmwv6a94Dx2k0YwKoSHdI1ChQeuYVKmTtQOQw6sDpz4mGg0OXHBW4FJQrJnDoetmPQTsxXQOQ=,iv:kRNMZ8TpfjjqX7z9e/X6Rifcnh3aSajAP+2Ct7ldzrE=,tag:uOeNt++8Xxufz9SL12zMJw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
