apiVersion: v1
kind: Pod
metadata:
  name: util-avarath
  namespace: media
spec:
  nodeName: avarath  # Change this per node
  hostPID: true
  hostNetwork: true
  containers:
  - name: util-avarath
    image: archlinux:latest
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: dev
      mountPath: /dev
    - name: sys
      mountPath: /sys
    - name: jellyfin-data
      mountPath: /mnt/jellyfin
  volumes:
  - name: dev
    hostPath:
      path: /dev
  - name: sys
    hostPath:
      path: /sys
  - name: jellyfin-data
    persistentVolumeClaim:
      claimName: jellyfin
  restartPolicy: Never
