apiVersion: batch/v1
kind: Job
metadata:
  name: disk-wipe-nvme
  namespace: rook-ceph  # or any namespace
spec:
  template:
    spec:
      restartPolicy: Never
      nodeName: avarath # Target specific node
      containers:
        - name: disk-wipe-nvme
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              set -ex
              DISK="/dev/disk/by-id/nvme-KINGSTON_OM8PGP41024Q-A0_50026B73825EEFAF"  # Change to your disk
              apk add wipefs sgdisk coreutils
              echo "Wiping disk: $DISK"

              # Remove filesystem signatures
              wipefs -af $DISK

              # Zap GPT and MBR
              sgdisk --zap-all $DISK

              # Optional: zero first/last MB for good measure
              dd if=/dev/zero of=$DISK bs=1M count=100
              dd if=/dev/zero of=$DISK bs=1M seek=$(( $(blockdev --getsz $DISK) / 2048 - 100 )) count=100

              echo "Disk $DISK wiped successfully"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dev
              mountPath: /dev
      volumes:
        - name: dev
          hostPath:
            path: /dev
---
apiVersion: batch/v1
kind: Job
metadata:
  name: disk-wipe-ata
  namespace: rook-ceph  # or any namespace
spec:
  template:
    spec:
      restartPolicy: Never
      nodeName: avarath # Target specific node
      containers:
        - name: disk-wipe-ata
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              set -ex
              DISK="/dev/disk/by-id/ata-WDC_WD141KFGX-68FH9N0_Y6GJZZDD"  # Change to your disk
              apk add wipefs sgdisk coreutils
              echo "Wiping disk: $DISK"

              # Remove filesystem signatures
              wipefs -af $DISK

              # Zap GPT and MBR
              sgdisk --zap-all $DISK

              # Optional: zero first/last MB for good measure
              dd if=/dev/zero of=$DISK bs=15M count=100
              dd if=/dev/zero of=$DISK bs=1M seek=$(( $(blockdev --getsz $DISK) / 2048 - 100 )) count=100

              echo "Disk $DISK wiped successfully"
          securityContext:
            privileged: true
          volumeMounts:
            - name: dev
              mountPath: /dev
      volumes:
        - name: dev
          hostPath:
            path: /dev