# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: vaultwarden
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 65534
            runAsGroup: 65533
            runAsNonRoot: true
            fsGroup: 65533
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/dani-garcia/vaultwarden
              tag: "1.34.3-alpine" # {"$imagepolicy": "flux-system:vaultwarden:tag"}
            env:
              PUID: "65534"
              PGID: "65533"
              TC: "Europe/Budapest"
              DOMAIN: "https://vault.${SECRET_DOMAIN}"
              ADMIN_TOKEN: "$argon2id$v=19$m=65540,t=3,p=4$s/puDHon6Vh5Ba1QCvRIie5du44J+EtVj9kn/B8cQ1k$xR9nsC5Rk2HN+UC/eMVaUDwQVy27jug8X6+MNcEHRw0"
    service:
      main:
        ports:
          http:
            port: &port 80
            protocol: TCP
    route:
      app:
        hostnames:
          - "vault.${SECRET_DOMAIN}"
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *port
    persistence:
      data:
        type: persistentVolumeClaim
        existingClaim: vaultwarden
        advancedMounts:
          main:
            main:
              - path: /data
                readOnly: false
