apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:JxPqbCY0p6HgnQrzPkTDekJO1oZN9XNdyc1T0f3kLH8AtBp7DzZ3LpVcz/dWvTEnHeGHcalOqLbvsraDTlayogsOCI6+PVqgHwAT8X/mHRpXV84hXMZmG03lBmychybd7F4eUmGlVGvVueUun+C8VIMZ6vJG/uz00VJw4OVaTGY7F89R2+uPP1D8KebdGbv0WiAgrG4fbUjDrDSDwBiPkFxZO3zIk5TG3m8gUh5B938X17zX,iv:W8nkQcucjK+8IkhN2So9vfSQKGKfaiKrh7KL1aK/Qz8=,tag:SKDmoqPznECSnUArTuf+ag==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IElvMTdhR3c0
        Wlora1pRcHdnZng4dGFvR2J1SnpoNUtzZHFIanR3Sis3Zi9FNlZrcEhsQXNXSWZu
        MUVqNVIrQzlsa1loZFJDNjRodERldHFBRjM2d2xUaytsU0lvdjRRR0dGZlI2eXEy
        b2FhaEZISExhVzJrWXpnNFpLUUorSXRqWXJIR1VnQTJuTGxsTW1GbEJteFlYc3BJ
        V0pkMUlFTmFoeFl0NE9SYVRORFh0dkRuODZXL1VOU0tWaGtzb3FhZkNvb3R6NUFk
        dFBrM09jbXpoeENZSEIwdG9qNmdEVkdNRjNxLzZqZ3JmOUYyTWo1b2FNYWgxdER4
        bkFyMzZoalBiM0JMSWRQSFRmeHdLUkZKeUk2SE1rYTNwWFlvcHUxRHUrSE9Oa0dJ
        OHozZ0tnRjdDa3kzOC9YNGY1YWN2RGkvWGRhckIxcDdkK1BGYjVJSC9uQTU5eTFK
        eFB1NUkzMXZJMm9VYlY4RXV4MVR2VGFLZWdzVkR3V2RJMXVxUWlDNUVzbHl6Wis5
        NWMwNW5EMjBSVHd4VVZIeTJGSWJSMU1BcDNrLzlacVJRVHE4cFJiVVlNRmVCVHR5
        Zy9GZ3lCZ2s0OURFREdobzN0MlFiTEhXRFNCYlJwVTBVc0FKL3RRa0NHbmFRcXRS
        YVFFMlZYQ09uRW8rbEVCbHlJaE5LcCt2SEdkQ2JsTlg4MFpZSG9Oc3gyY3p1NWcy
        ZjNwN21aSjVXZ0hpYmVDWjNPem9UUisrVlE2NklCWjA5blR6dWNvV2JWdkhGQmJm
        blphRGVmQk5oa3B2NkJ3TU1RRTdCTzlaL0ZnWTJ0RUhvcWpTOGQwVnhMZSt1eHI0
        TnZNV3AzU0VaSnBlRkJnZEVleUlEYVMyWmJYN3JhaXhhVWxTbFlMTVJIc3J5dlFQ
        RHNxZ0FSVWdVV05zaDdFRXVhYmd3bFlPT2JhZTZPaFR0SU92TEdWWXhtbS9CVGo0
        bUZlR0hUcXFSYWFuSUo1ck9NK3NwRy9qb3pMZDJpRkRoR2NMaTF2U004Q1YrNEpB
        MDRPaWd3bVpqWERrTDhPU1NWdjJ0bmRRT05qYjAvUUhGSDdObS95amhpNGpjclJX
        VlFsQU94VGQxcW1EMzFuQ0VUaVJIbnk2ZUdxVDZpenY1Tkc5RnAvZ20xeGsvdDNC
        c2pBS3J5cDhra09hemxhWTZMMDdKa2UydTg0VUpVdG1kS1VXZjJtQ0FTbFpRdDlj
        a2Z2UGtEUjRPcDRTMHhEV0JRWGpWTWZBWUVXVzV3VHRJbmJQaVZuM053NHJaTGFB
        Z3FFSitaLzdYTnpFUkFCR3VialRseVQyTVRNY2NuK0ZScThGbEs1TFEzdmJrMjVJ
        SzdHd2hwSlcvdENYUktwdDBMb0pJdGs4YUw0cjhHdXNFWnl2TWhRVzRxN3NvQW5E
        VnhMYVZjcU1jRElxMkhUck9IYWxqQkd0S0JZUnB0T05YZDZic21vVmdoOWRMZHBK
        YXAxZU1HOFZpVzZMOWNwR3VIbzlhVmRPUWRlbzZ4UmlSalRIRmI1dDJ2Snh6dWlm
        bmlaQjRxWnNsbFhWWmo1L2g0K25vMjRqMHIrdXRIa29QUTMxNnlOdDRXcDFJN1VB
        bGd3c2pnR0xXWjNQK1dsV3cvVmxmcUhQZi9rUHl3Vys2ZFlkMEE5NHFTbDRIbVpj
        RTUwVDdaNDF6OHJSOHN5ZVQ2WHJUWi9QRklXTk9lQVRwUkhPeUsyTFJmT1NnV3ZT
        aGhxZSsxbmpxVFJGRDBDR01sdzZXUWdEYXd2dGJWcS9sbUZtMnJlQUhSRzRYR3hT
        ZStvdDJobWpBRzdqckpBekhSM2RlWm1zOFdPMURzYmdwajhXYUpodTZFTGNWM2Nk
        c3pvakQyTGtvL0I1YmN5Y1hiSWo4WDZGTFltdTM1UklpOEowNDJjN0ZmZDhlTG8w
        VTh2QkhyMkhQTHl0dWhnVjU4VXcvN2RkUU5MRVhrNHBodFJHZnJRVjR2aWdLZwp2
        a09OSU9zUUl2d0VUZmNhblNkQWFWay9mTE1jbVpWenYwQTUwdkg0amlZCi0tLSBD
        enVFRUFtUktGL05zNlNUZlNwZGkrL1NjdEIzWmxjSE45UWRtRDZYTnlvCi0BihlK
        W7npY60s+VrKpR30W1ZJSl7fn3o890fhWI9OZzoZvAtvKKeemh8mUS6LN3JiwTez
        C9Q9Az2lXkI8fTM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14wqvmn43wc3tquc22uyme4sgy0kyswdzcqlqj5xax2ftqsdwfs24s8a48f8nc0k6xp8a844zq3x20sj3p5q4htg203sy0am3ccng7369nm0mfjqt5lp9f2grzjsev7ktyl0zj9puz260864l0kktswsgwrwr8jyw2jurxjs2f7ys8mpg8urxfjfw5wggyeskg5j34x32hhtnk2kpugj4k3vx07s3a7desr08rn46jk03mc4qhkdq76sf0jgy02m76uz9l5y7rjd34y4vy5znya3j5q8q74sq2pqffy7uxcxrctuzgywvwdwptwq9yehchmhskgt56yfhedgae0nt489n3ld824tf73efvsgset2kkdneqtaaqs5t2zzk072jal2eg60n3e7adrjwgkvpdr99jleckkm48g7urry8v35s47v32a5qa75yk486sz650vxnany0jxjrl69kzsx38d4sg8ph4ccsf5f3sqexqm7fds55ckk7s958v2uhcwcqguve2f2k82g5yfzz8n9kllzjw5y9y485xguawkw0clqh3k5s4a06jya2esejuxjatccf4jznf55f4xjvwjj52gg38l3ksa8jfp3mvxqy0324nkaslnm96k56ve0ekjung42jpwjmuhmrnq22ynmq8ffk2wv5rd5578gvtt09hqr0x9h0lznjy5s6p6q9xqfhpc05g5h9k63grec3amvny6y8jjkpfqgpuhxk24ejs93ech3s5ycqj3w3djs52x2pksu9lvczz66z49vruu2uus4tapncmkxm4p905j7qr2xq62z8df6vhf3ugxcekngqvc6g0y958s3vnzs9w6vaj0v4vddke4thuwr5rc033r7v8tgjg6jw6u3e7kqyfjqjnkdy5x3z9ww5d399fw6sjs5sf23lty4x6a6v9nyt4043yq6fprajg9rtu77x2qth6stfl896va5p59hcguv5079pmlgc25a8zuwrzhjvvxvarc5qjcgt7fa8h6aacr7jax529f68gv2vm37ejphlssxe928rkuezdzur7pzpem6e2jrrdqrvnq39mwd85lm5ncgkxdaz0d67mcza9msmerv8jfcs88y7w48zk4k9wutsasgfekdkjq9r23xgczgplvfga9hxzxm2z6xvmjmp7hquc95gmckpv5vzvux7hxjws2tl8z2vgm6vckhvq8rfljc9f0qdq6wy2w8sxl3mp25g5sd3h9afaa5ggd7g98wkryqh537a0faa359mh722seg6f0ssqwzm7y49vjvjra46yjc3zwqzp0ygc3gtnrrhs9yesm56frevzprd3yytqm4thv3fhdmexgv465a950xvlptk4s0hte6wzzskyj3scdtf0qjkjv25tn5ggc85wfadngz6jpjhjgm5c44ad3uqhgancst7f5dhw7dt5qs0q5p0ffaaejj9pv99fqegrypejzuuffhajpprtm9frx795umkwd2rgzhyxwnrez2z8yyvcctgenslapqq9uyzjk2t3hus43sfpxcg8fakques9kpy4v5pck4t2ajn8gtph3pquva984pqjq7mwxzh3sth5qdc722g5zztsxc90qy8sf4844p2k84kjv7jczymzhxvf2aqpfm2jgyze2qk8euzkx9l553nfaayue5el3dhyus8gu2cjfme4jzknl6p9zshr2cg4wfpz45t3xr2qh4tqplcvgqh0shye9rza2rek4j2ashjrrf4f8k7p2d32u6tq7v38j9jzn2lqw05m0q746q23kfvl2mxsyqant2uhg0fhzngete8kjcc0ughw7hluzklsqxwz3f5m9qvy9qrdfrmq22s7n4wqvrts3wtzhxpe09ngzlc76qmam7jlkrx59834ngt5w2j4wjk85wvrjrnzzra4nf2m2hdv8nswvhf39lr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T07:18:43Z"
  mac: ENC[AES256_GCM,data:dCFNvNr1bG2UTIh/jIOOaXywrsI/WkcMqiojibZu9s2AH+lPpx3zf+Ay/Q+/LDf98N4v0SNACN3Y7zUqXKFONhZEN6hz6PcgWoWs5IuJPxkQXFzIHrsBtU7C9hp+X+vAFfb6wsNrxppEGC6bt981ySp/LfRk/szvItIqVxxRCuc=,iv:UGZu/YhvUTsHeEGBzkjx99GRf00w8wr057wWrc+KieI=,tag:Ra6FrizCQ1wr4lczDkHljg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
