apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:BzvlHsuIbIUUwtvI6a9f6Mkje2PKaWaBSHlPKHFdhibBMGbQ7XtkslwF97pq+Cg32BcOvH3pBV+1YegIp5OnTjTqZbu6qgsbZ0GRcxZWch/wT5NvdfpuNWjNwbKjcYUFM4BZXzj4kJOjgGC+Uk+63aI5JXQvzWggEm3jU6ToocpTQsnN5EP26OHkqkxoQhQnFZNsUC5CYivTYD4LDM2Wi7aPybiLB8uNcrdN44X4Ae0CxYlX,iv:UzS/MHp1/0OC9rp2DHljJhuocJk1xnw+Kli7Eiog6TY=,tag:1rFpGJrjYCRGFqHcoxRt9g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEFINWRoTkF3
        Y1VMcHhHVTNUUGEzNVpBZE9laUxKWkJlNjlGa2NiSlFubk9KWWNCcXJnNmVwV1Ni
        dU1TeFl6M3NGeXRqOEVtSkhyNVVGakNveTc1Qk5iVW4zSmVnejBFZHpmdEJObDBC
        UWFMemtraWk2NFlGb24wZWRRRXpxc3UzclRqMXZLS3VMd2RkeDZFUkx1UUExeUxJ
        TmdYRG14SUlpaHJBb2llN2ZxTWFCT3pmR3lteHoxc01rTk9nL2F0Y1BZOVR0WmNz
        ZUJKeisyRlM1K1BKTldoUy9LK2RFdzc0S0tFRFNqQzNpSVhuWEl0dm5BYURPbVVS
        YS9LeEd5dUJoVEhvZmxYNEx1OWNESGpIVjJrbTl3VnBHbUtZRjNHVExZSzJxSG9F
        MVBSdm1DbkpuR1FmQ1dpeWg3aWxQcms4OHNiL3Nsd1dpN0Y4QVBLTlRLazNkYWhr
        bS9aUHZSSUFuT3NhNWlBRHc1dXJCdTg3VExXOURoMWdpaWQ2S0Uvek0yMVhSZE9y
        K04yc0toQ1g1VlN0ZzloczJZWnlGNHA1YzdiS1JFWWlOeWJWOVZoUnpTOXFkSnBX
        K3Z3S01HWjRCQ1RqUnBvZS9LYm5HNlVHL05wSUVQZWk2VjJSU3lVMWVYUVoveCtG
        RWlKTVNWTEx1M1pGcHVHUWlGZFk2ZzdtbFA1U0FjSnQ0RmRGSzlpWWdFbDhuRlA2
        cWxyY1dHdFRHYnlFbTNKakZseUErMk0zaEJGVWdwREovZHNSTUN6ZEltSWZZMXNF
        UHBLM1RsUythZzVvbjRQOE9waUFZRjE5V0RJZFV5aEV2Z1dsaGFRc3ZQbXF5Ylpi
        T0xvN2lZcHp0VGN5NForQW92V0U0R0h2b2NwSU1ydDdyUkpzZXBKZXoyTlUwdzRz
        SjZwUENvTmgrWll0QTlVZUxCT2lVYlZhNHlzeWJFRTN5eHFIZFFiSGl5SmVCZ2VX
        OG5tb3J2YzBHc1JDV3d6ZWZFODRKa1d1K0RkemtHVmhycnQvYVB5Uzh6UUNrd2Yv
        a1ZrajBNMHQrQ2lJWlBWUVROVllIRHRTcWdHeXlCRFUxNnpETEVmZUdCQnpROG9o
        ZWxvTWp2WkYyL0pGSlI2Umx3Tksxa3JIbTRxcU9XWDBOVit6cEs4YlRDL0RRU2I4
        WGhBTVYyckxxRTNzY2dRNVhVSGZiajRjWmhOTUFhSGtaVEN2a1l3VUkrVVcwUzlI
        SXU2REhRQWY5Ni9qK2xYVWZjdjVFZTV5MFhFZE41NUdBQUsxVFAraWk0YkRVQ0dS
        Y3pDNUZVc0ZWUDh5djgxWFhTakY4ZlpiRENGMC9SNGxFRytLQ205VUp0VFVjMG5k
        YkdBMjNYTkZXWFArd2trWXdhZUVMZ3hSNTF3WisxK1dXWFdsbm1aaklEUHlwTFJm
        WEpXSnhuTW1VSkd6aXdKRVhQVTVqUWppeVFaU0xScDVNa3NiZU9YcG44bmd1QjQ4
        bFNJM003TUtRRE84Q1NyWG5zeGlqRlVhQkhpMy9YdXByMnpGWFBuVDVqOS9GRXdC
        NjM3SmNtR3phb21EU2RncGpMMnlhVUQ4a2hxSUd3dFVkNHVueEgrVjkwdEczeTZy
        OWg5Mnk0OG9hQXVLSVVkYVhLbzQvRHVCTU5WWXNRdDFsWEhDR1VYNmY3cmFXL3cv
        V2Rwb1hjR0FEc2JXNHJSeDRZMG91cm5HaHowbWt6MExSUnMzM0h6OWRiY1gyRlV1
        eWJnWTVCRUpDTW5vZkxWUDhoU0MvU1ZoTmo2TXZQcXVZNVVNS1hxSW5JSzJ1MnJa
        Ym1GbmI1d2VrQWc3NFJTbmo4SHFjci9wc3VabUlIczZSLzlvWWZIenIyZjR6ejJt
        YlN3ZzA5RnFQK242azMyNmhsaGRCTmwwb3ZDYkVUVDVpS1lMRWFKOVpLZ1FxWTBi
        V1M2SkM4UDQ3d1Zra2huazdLUnVNVWhFeS9uNDg0U1BxY2ZFaUhCZWVreWRmdwp6
        R1RyWHRYcE5EV1JNRE0zL21GNTBWUU5zTTFBeHQ3elZZSXVsNkNKNUxvCi0tLSBC
        QkpXbTFXUVVYeDhseFJlSFJCS2pNTlJlK0RmRzVkTnFiWkk4K1lNSTEwCu+9ZMtb
        qSFxPzGrkuRcPxGVDOMJE+zyAnpYmudMjz1znpYuJTuZ9Adap1AHs7PGrkZvcZ4p
        mA/CO/d5QADEi40=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14wqvmn43wc3tquc22uyme4sgy0kyswdzcqlqj5xax2ftqsdwfs24s8a48f8nc0k6xp8a844zq3x20sj3p5q4htg203sy0am3ccng7369nm0mfjqt5lp9f2grzjsev7ktyl0zj9puz260864l0kktswsgwrwr8jyw2jurxjs2f7ys8mpg8urxfjfw5wggyeskg5j34x32hhtnk2kpugj4k3vx07s3a7desr08rn46jk03mc4qhkdq76sf0jgy02m76uz9l5y7rjd34y4vy5znya3j5q8q74sq2pqffy7uxcxrctuzgywvwdwptwq9yehchmhskgt56yfhedgae0nt489n3ld824tf73efvsgset2kkdneqtaaqs5t2zzk072jal2eg60n3e7adrjwgkvpdr99jleckkm48g7urry8v35s47v32a5qa75yk486sz650vxnany0jxjrl69kzsx38d4sg8ph4ccsf5f3sqexqm7fds55ckk7s958v2uhcwcqguve2f2k82g5yfzz8n9kllzjw5y9y485xguawkw0clqh3k5s4a06jya2esejuxjatccf4jznf55f4xjvwjj52gg38l3ksa8jfp3mvxqy0324nkaslnm96k56ve0ekjung42jpwjmuhmrnq22ynmq8ffk2wv5rd5578gvtt09hqr0x9h0lznjy5s6p6q9xqfhpc05g5h9k63grec3amvny6y8jjkpfqgpuhxk24ejs93ech3s5ycqj3w3djs52x2pksu9lvczz66z49vruu2uus4tapncmkxm4p905j7qr2xq62z8df6vhf3ugxcekngqvc6g0y958s3vnzs9w6vaj0v4vddke4thuwr5rc033r7v8tgjg6jw6u3e7kqyfjqjnkdy5x3z9ww5d399fw6sjs5sf23lty4x6a6v9nyt4043yq6fprajg9rtu77x2qth6stfl896va5p59hcguv5079pmlgc25a8zuwrzhjvvxvarc5qjcgt7fa8h6aacr7jax529f68gv2vm37ejphlssxe928rkuezdzur7pzpem6e2jrrdqrvnq39mwd85lm5ncgkxdaz0d67mcza9msmerv8jfcs88y7w48zk4k9wutsasgfekdkjq9r23xgczgplvfga9hxzxm2z6xvmjmp7hquc95gmckpv5vzvux7hxjws2tl8z2vgm6vckhvq8rfljc9f0qdq6wy2w8sxl3mp25g5sd3h9afaa5ggd7g98wkryqh537a0faa359mh722seg6f0ssqwzm7y49vjvjra46yjc3zwqzp0ygc3gtnrrhs9yesm56frevzprd3yytqm4thv3fhdmexgv465a950xvlptk4s0hte6wzzskyj3scdtf0qjkjv25tn5ggc85wfadngz6jpjhjgm5c44ad3uqhgancst7f5dhw7dt5qs0q5p0ffaaejj9pv99fqegrypejzuuffhajpprtm9frx795umkwd2rgzhyxwnrez2z8yyvcctgenslapqq9uyzjk2t3hus43sfpxcg8fakques9kpy4v5pck4t2ajn8gtph3pquva984pqjq7mwxzh3sth5qdc722g5zztsxc90qy8sf4844p2k84kjv7jczymzhxvf2aqpfm2jgyze2qk8euzkx9l553nfaayue5el3dhyus8gu2cjfme4jzknl6p9zshr2cg4wfpz45t3xr2qh4tqplcvgqh0shye9rza2rek4j2ashjrrf4f8k7p2d32u6tq7v38j9jzn2lqw05m0q746q23kfvl2mxsyqant2uhg0fhzngete8kjcc0ughw7hluzklsqxwz3f5m9qvy9qrdfrmq22s7n4wqvrts3wtzhxpe09ngzlc76qmam7jlkrx59834ngt5w2j4wjk85wvrjrnzzra4nf2m2hdv8nswvhf39lr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T07:12:03Z"
  mac: ENC[AES256_GCM,data:3FBh/cwYCiZVPikqvnInJiH1N+3furfi1hNLIMq/8WwTfSP85aU2SFASt2ujfAygxdKwYhStDbGG+6+UUGWT4dID97CFM0vdX0aCsLdGdT+RFPkZIGwG7IFwuOUhSdsXO58t2hRBPc265uP3eO8I0et2GxyT6c9OAkHhW5uo80g=,iv:C/akTAHR6jtY+47eTZviAOZVpSnfKd3bMtUq5DdhZH4=,tag:TAT5fm7SBDm1Yr2nv1l63w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
