apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:jZ+DMTa93watg+iJS+omPEpOOvWZKIh79hDnHVR8v97cQll0LSYO8OoyFJVO5K+hj/eA2WR1LOKd458OKpfnRy1FBJXuSHVVRbeyTRLS1sFZPzlYNaLsQjRPzQb4JmUozbx+rj1tP3XxBYTS/UtV3ABa/NGUGaAFLy38p11nEAWg3CDa0FOZPs9yjnwOZFD7czUSlesRdRYcSIAjthnMgAKw62YUWy/KVorKKx/bX1rdayRw,iv:umCX6qAdSCU5mpjKbEzkbXRjovIhCsRaZvXBxSoKJis=,tag:QLKZo4lc9rY1xaxz7C2H4w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IERFUDZTRTNP
        N1UzNHJLTWtJamE0NHBaZVVoeHhJNTRSMjJDSzMrVi9QdWExME0zWHJUZWN4aHZC
        RXZYWkorWDZsYVlvWmxCYjRKeWt1ZUNHVWlZcHRwMDFlVjIzL0dWeTYweFFSbmVo
        NUdDNFhmWitRc3ZTOE5ZTU5Ra0k1cWJIL3dDRjczcjJjVkRsckxwdGRjSmZKSU9t
        SzczTDM1LzErSHlJbEJwR3pOZ3FzMHJRV3c0djEzVEZhRHZldHVXSUxHU2tTOHZV
        VjBORXpFVnltTEpLV1J2SEdzS1huczRvR2I4dmlNNExnMUVpME9TQmw3cUNxaDU5
        UkJjbWd3ODlqNjJQaWp1QThjMThrMitVcURVdVhhTFI3M05UdGp3dDd0eVNuY2dq
        TUllTjBYUG96YVVuVmZNL3RBeFZQQVljUHB3cnprd3pESVZ1TEVPUXE5dXFGV2pS
        TStkM2hXYmttRHZOZitPbXVhcnBGbFlBcm1Wc2NzbEM0ejVIR0NKQ3ZuWlRaRWQz
        MVBIdCtrRkJDMzF6TWJZS3ZhM0NxcitKTWxvNUJXbndqeUZWUytvMnFJcmx3WDhR
        dUV0SS90b1AzZXFDdnptM2IzcnFPVWxUWkJqUEFrZ3hEOGVrS3VoT2E4M2x3MlUx
        eVI2NFRWLzJuSStXSGVqcWpaUU1GNlg5VjB2QXVLai9ZNll0cGJjMEhmb3lsallO
        aHF6N1ZRcklIa1JuSXlYNEZzZG1CcG1WRWVtVTBOUENTZW1rL0s2eFh0bTh3OWd6
        aTc4VllDdGZ2QmtMc1k4MHQ5bnRlRGVuSFR0U1dFd1JzaG0vRFN2RXJMZnd5VjI2
        RVcwKzdXMERjK00vSkJmbmZsSTFhUTU1V2xGRFhLa1NGbVhSU096UTF4bEovenZ2
        RjJmdFM3UXp5QzRKQlF3MXowV0xWYWIyZCtwUXRsa0RTWVZkUFNmN1JuRFlVbFpt
        S1BWRTdjVzEzMHJ1SEVtekZJVGhkdGdsRGFPNStBRlVKcDBQdXRaRHlVVndGZXZH
        b3FlajZLTzUyWjliOE5KSzdlQkJmSDA1RHpoQUhLcGZEK3ltK0lVR0Z6RnlaaWUr
        YWpXMnU5VFZ0YmtZdUI5WEZ1Q1hocXBPV3BrTEszbForUlc1M0JXY2NMMVptZVZG
        OTJOZjNwOXVNT0VHV3dsdU9vZ2k2WWg3TUZadXVoaUpXbDlPT09lZ1VDL3hBdUcx
        U3VQMHNBM09yRFJNYS91TTlYWXdBYVhYY2h3Z3g4dWpOcmZWbkNIY2UvOThLRFNv
        Qlo4SmhTT25xOE9CZFVBbmxLYmdvaTBXRG93U2xzbzJYU3YyYkZ2WFlsNWRvUTJD
        ZS9rZTBnUWtnRnpOTGc5cXZjMm5QNjhjaG5KM1ZqTVZFMnhGakpsQlZpTkk3Q2VT
        cVZEaytjQXVGcDdrVjRuYjloVURWcHVUK04zUjVRSU0zc2JnZ1Y0dnROV21xcGQ5
        RWVOMDR1d09LMjJkMTN0WWpScmxwcUNZeFp2YkRRK1dEcGFOVDdsLzVtNHFlREFw
        clJmajFXYmplOFFwTVdVNjhMT3NBZlQ2Z0gzRkpYQjVCU3Vvc0UrZlM5cS9qb3RT
        ZHV0TDFjMlVKWnhENGlvV3ZzMHRYelJCbS9yYkxlY0hKRFpUQ3VKNWQxNDhpdkh0
        SWtCaXJzNTV5aEhua3JERVZVYTY0VUZWeEY1MHBybldTR2Y4ZDd0dGJ0a1Iydk1o
        by9xQ05HYlRCVGhlVGNTTFk4YksxVjZWdjZqZGtUdHZJY01Lam5MZUFtWDJuNkUw
        dUsyWFpSeHNDMXFLQi84MTdzUllyTTdjeTZkL0ZLd1JhbWFPQ3NrQ2NyakdoenNE
        NHMvY21SYmRvZTZUdWZUZVRDTkVXMUNPSkVkOEVSZkRMRUpyVTZSVmQ1ZkhCc0Nq
        dUVoK1AveEZIc2JHVk11amQvbndPSGt4cUpBdllvdFE0bkJUYUcvSVVRbEZUUQpq
        eVBheHNNUlE1LzFRZlJCOCtOQ3owUjFTSEV5Y1pJTFFuOXFQK1o2TFZFCi0tLSBn
        S3EzajFmdnlRT3JuT0xvVnFCRVRXQTFEMHU3VzFiYlJ5am9zYnQ1bk5RCqHOXupf
        Jb2Sb1jpa9f9Do2blvkYuS7RVGE2qoNM7+sjfdbEnHDi72E6BOY2PUoVceOdwZfn
        2NehFSSr2UCCmZQ=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14wqvmn43wc3tquc22uyme4sgy0kyswdzcqlqj5xax2ftqsdwfs24s8a48f8nc0k6xp8a844zq3x20sj3p5q4htg203sy0am3ccng7369nm0mfjqt5lp9f2grzjsev7ktyl0zj9puz260864l0kktswsgwrwr8jyw2jurxjs2f7ys8mpg8urxfjfw5wggyeskg5j34x32hhtnk2kpugj4k3vx07s3a7desr08rn46jk03mc4qhkdq76sf0jgy02m76uz9l5y7rjd34y4vy5znya3j5q8q74sq2pqffy7uxcxrctuzgywvwdwptwq9yehchmhskgt56yfhedgae0nt489n3ld824tf73efvsgset2kkdneqtaaqs5t2zzk072jal2eg60n3e7adrjwgkvpdr99jleckkm48g7urry8v35s47v32a5qa75yk486sz650vxnany0jxjrl69kzsx38d4sg8ph4ccsf5f3sqexqm7fds55ckk7s958v2uhcwcqguve2f2k82g5yfzz8n9kllzjw5y9y485xguawkw0clqh3k5s4a06jya2esejuxjatccf4jznf55f4xjvwjj52gg38l3ksa8jfp3mvxqy0324nkaslnm96k56ve0ekjung42jpwjmuhmrnq22ynmq8ffk2wv5rd5578gvtt09hqr0x9h0lznjy5s6p6q9xqfhpc05g5h9k63grec3amvny6y8jjkpfqgpuhxk24ejs93ech3s5ycqj3w3djs52x2pksu9lvczz66z49vruu2uus4tapncmkxm4p905j7qr2xq62z8df6vhf3ugxcekngqvc6g0y958s3vnzs9w6vaj0v4vddke4thuwr5rc033r7v8tgjg6jw6u3e7kqyfjqjnkdy5x3z9ww5d399fw6sjs5sf23lty4x6a6v9nyt4043yq6fprajg9rtu77x2qth6stfl896va5p59hcguv5079pmlgc25a8zuwrzhjvvxvarc5qjcgt7fa8h6aacr7jax529f68gv2vm37ejphlssxe928rkuezdzur7pzpem6e2jrrdqrvnq39mwd85lm5ncgkxdaz0d67mcza9msmerv8jfcs88y7w48zk4k9wutsasgfekdkjq9r23xgczgplvfga9hxzxm2z6xvmjmp7hquc95gmckpv5vzvux7hxjws2tl8z2vgm6vckhvq8rfljc9f0qdq6wy2w8sxl3mp25g5sd3h9afaa5ggd7g98wkryqh537a0faa359mh722seg6f0ssqwzm7y49vjvjra46yjc3zwqzp0ygc3gtnrrhs9yesm56frevzprd3yytqm4thv3fhdmexgv465a950xvlptk4s0hte6wzzskyj3scdtf0qjkjv25tn5ggc85wfadngz6jpjhjgm5c44ad3uqhgancst7f5dhw7dt5qs0q5p0ffaaejj9pv99fqegrypejzuuffhajpprtm9frx795umkwd2rgzhyxwnrez2z8yyvcctgenslapqq9uyzjk2t3hus43sfpxcg8fakques9kpy4v5pck4t2ajn8gtph3pquva984pqjq7mwxzh3sth5qdc722g5zztsxc90qy8sf4844p2k84kjv7jczymzhxvf2aqpfm2jgyze2qk8euzkx9l553nfaayue5el3dhyus8gu2cjfme4jzknl6p9zshr2cg4wfpz45t3xr2qh4tqplcvgqh0shye9rza2rek4j2ashjrrf4f8k7p2d32u6tq7v38j9jzn2lqw05m0q746q23kfvl2mxsyqant2uhg0fhzngete8kjcc0ughw7hluzklsqxwz3f5m9qvy9qrdfrmq22s7n4wqvrts3wtzhxpe09ngzlc76qmam7jlkrx59834ngt5w2j4wjk85wvrjrnzzra4nf2m2hdv8nswvhf39lr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T06:31:48Z"
  mac: ENC[AES256_GCM,data:umkDpNH2F26m2SgKALSh3LbdkKJrkERuYQ45eZHBL7et4rUm9QmL2gtwm2yQF6zralBqg48lIzhFiqNSQ2pdJfSJDM2ulpLvTw3Nh6trNRYerncpQEUMw+EjNikLqP/r5n0LbciBAjcoOqRl+HWlWO63nM4U5MMSOTuNmRuMgMY=,iv:2qwVYSkTXRbPIe8yegd6qw3KjK/V4TOz0EmNVCy8tAI=,tag:iZAyPRWSBg0WUPP3HU4new==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
