---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:

  generate-config:
    desc: Render Talos machine configs locally
    dir: '{{.TALOS_DIR}}'
    cmd: topf render -o output
    preconditions:
      - test -f {{.TALOS_DIR}}/topf.yaml
      - test -f {{.TALOS_DIR}}/secrets.yaml
      - test -f {{.ROOT_DIR}}/.sops.yaml
      - test -f {{.SOPS_AGE_KEY_FILE}}
      - which topf

  apply-node:
    desc: Apply Talos config to a node [IP=required]
    dir: '{{.TALOS_DIR}}'
    cmd: topf apply --nodes-filter '^{{.HOST}}$' --mode={{.MODE}}
    vars:
      MODE: '{{.MODE | default "auto"}}'
      HOST:
        sh: yq -r '.nodes[] | select(.ip == "{{.IP}}") | .host' {{.TALOS_DIR}}/topf.yaml
    requires:
      vars: [IP]
    preconditions:
      - test -n "{{.HOST}}"
      - talosctl --nodes {{.IP}} get machineconfig
      - talosctl config info
      - test -f {{.TALOSCONFIG}}
      - which topf talosctl yq

  upgrade-node:
    desc: Upgrade Talos on a single node [IP=required]
    dir: '{{.TALOS_DIR}}'
    cmd: topf upgrade --nodes-filter '^{{.HOST}}$'
    vars:
      HOST:
        sh: yq -r '.nodes[] | select(.ip == "{{.IP}}") | .host' {{.TALOS_DIR}}/topf.yaml
    requires:
      vars: [IP]
    preconditions:
      - test -n "{{.HOST}}"
      - talosctl --nodes {{.IP}} get machineconfig
      - talosctl config info
      - test -f {{.TALOSCONFIG}}
      - which kubectl topf talosctl yq

  upgrade-k8s:
    desc: Upgrade Kubernetes [KUBERNETES_VERSION= from topf.yaml]
    dir: '{{.TALOS_DIR}}'
    cmd: talosctl --nodes '{{.NODE}}' upgrade-k8s --to '{{.KUBERNETES_VERSION}}'
    vars:
      NODE:
        sh: yq -r '[.nodes[] | select(.role == "control-plane")][0].ip' {{.TALOS_DIR}}/topf.yaml
      KUBERNETES_VERSION:
        sh: yq -r '.kubernetesVersion | sub("^v";"")' {{.TALOS_DIR}}/topf.yaml
    preconditions:
      - test -n "{{.NODE}}"
      - talosctl config info
      - test -f {{.TALOSCONFIG}}
      - which talosctl yq

  reset:
    desc: Resets nodes back to maintenance mode
    dir: '{{.TALOS_DIR}}'
    prompt: This will destroy your cluster and reset the nodes back to maintenance mode... continue?
    cmd: topf reset --full={{if eq .CLI_FORCE true}}true{{else}}false{{end}} --graceful=false
    preconditions:
      - which topf
