---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secret-manager
  namespace: secrets
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.secrets.svc.cluster.local:9998
      caProvider:
        name: bitwarden-tls-certs
        type: Secret
        key: ca.crt
        namespace: secrets
      organizationID: "3da4177d-b212-466a-b0c2-b34b007e417c"
      projectID: "1b749a52-c3e4-44bf-9af6-b34f01056f13"