# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-access-token
stringData:
  token: ENC[AES256_GCM,data:riq3GdDsPU9/RaEG1DO0npmLjGtV4b0jIuQAxqYODYtgYU135sEctYGtKePw5dsC1QvKbdXqjlAq0lFosIJ6x3iajNMpkAKtXCQwRDt2+m/RxUj8c0yKLNtBRFrRkA==,iv:4P8QaRZK+6rkwWgCQKm332gTw/0jJrOiUjPdmb5+Dxc=,tag:tTagSiOUCWj5O5IMKPXdmA==,type:str]
sops:
  age:
    - recipient: age17kkjwh97ech8ky6sa05xnyuxr9gpqwdjq8wjqc55a2mu7mdv9s8qvdfxpv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3d3d6enY5Vmd4NVJ0dEJQ
        alk4alJiWFdSWWJFMURJckY5bnY3b1YxOWhvCk8yZFhjYTEzWkFvTEJUeXdiaVpZ
        VUhKb01hczBhMkc1cStXQit6bWFVVU0KLS0tIFZoS0FJejBZWURubFB0d1YzSEhT
        S0JsVEtWQWU1Z3VtZ1RsUVpWY1BVSE0KpkQo0WTwy4oT0i5val3zLYnXde+n2ZVV
        pCWjO3llllYLSIMFP5emrA//2QmIJXFgnzDAt56iL4BagUjSaIo56w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-02T06:59:26Z"
  mac: ENC[AES256_GCM,data:VIVTNR+3WPSKplEXRs+sw4BkP3ysXmJhgP6QvsEYL5P2f7KF/lYUR/7VmH1Ha8xBJwinKAK9KbFth7uFyGe0rz2gxQNnNAEa3TFXwpWgTCCIOzRnKgG3JAwuX+zGJBQPSRM/s1Lm8nbQs4LqmVuvJydLrAaVSGeyH6T8br6R5iQ=,iv:90wjK9DnjHZTA1JO+LpLu75Bll23cqGD3OxtbL0aeM8=,tag:TKeKRHK0HDU46BazLW/ECw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
