# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.35.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-access-token
stringData:
  token: ENC[AES256_GCM,data:Qhf4kr+r1oDt28FUjxLS1yY20fKc5f9WeJOr4DmPX1WBzaQO8Sxl9nh2TPkRb6ow6XkfRSPcR0UWLb2/TyHTvGBhstyClNBZH60M7+gftZWxsdmusVeAmGLAzmEnaw==,iv:iOx8gb+0swq4lKVgRpYfJVMddYgmZU1Mm0t9ZaACHAI=,tag:Lv3Eh/NN6pa7FKHMZHPODg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFArZkxUaVZ4
        VVJSeWZETUpObnV0MWQvY1Bhb2hJa2hFRmtIRUNweTZaZ0I3ODBjTzA5VTlTU2pG
        ZDR2dmdPWXREK0dheUJCNDM0eHdpU3JnRkJsR3p1Sm9INFZJaGlZVk5STHR1VnAz
        WnpKY1BEd0taRnhQaWFQcFErTjJFU3ZpVmtQbjRZS0xaR2M1KzlmVkxvamJJcG1M
        ZFROWmxkTlExam15Unl4aHpZZWl5SnVDY1gwanU0c05uWEI0WHR6M3oxdjl5Y0ow
        cTBPSXh3dENVVStyT0hLdkdkQzVTYis3SWdHU3lUQkFhT2VTdjM4aVpGbnVLMzJs
        YUpxUkVvUmZUb2hRSEc2NURabGpWVHlmLzdLN0U1TFpmRzRtQU5FRFlHRDhsRCsx
        UktubDYwdEJIWUIva0VucDdWUmo5bmVqQmdjTUJKc09QWUcvR1o1YUFlUXAyNGw0
        ZHc0RWNXS09BQjZBMFdxZDBzcVhkZmYzTy8yei9xODRldEl3WUY1cW5YTHFUcm1l
        TVcvaFRONUtiTXZzRGZIaVc2US82NUViT2h0YVBRa1BxWmNxak5pTURyV01kNlpT
        V0dTY0hLKzR1WTNtSlI4MXl2dFROUUJTRVNldE4rL3c0SnZTdmtrc3I0UmpBT0Jj
        d2NabjdrKzM5Ni9uTHg1OFFJUXQwL0RKd3NYODV0Z2xXME1JZnFJc3pBRnEzL3Zi
        M09wMEF5ZE52Ty9IMFY0NjFKSVJXaWJhQVExYjV6UFh6MW1IZkt3Mk1wRUozdGdD
        end4dW5Kb04xSW9ZRUlLdVNIL3B2TlBtQXBGclBLeHdxUXkveUV2dFlpOW0vSXFj
        dlBPYTdNL0g3RW03RjFOa0dzWmZyellJY0NtMEpqL0tNQitMWFd5bFhGYVovODVt
        OEZHV0NYc1FNVW5wRzRKTlMxU3kxZ1J6MWpLRFBkVjRMeCtSa0o3NEJVSXhJcGlS
        VjdFY2M1ZU5JQk9KWWhjanFzS3ZMZnRFUnlnbWNleFlFTW56NlZrSFVYQkZUSUhl
        dlc4T283NnBkUXg4LzRFampkVHpNMUxaK0tYbm5qQjZGaEorOExUYjBPYWFvMlZu
        eVpqSit1bzA0N3N3R1UyRnNlaXFjYzRkNytVWHYvWUZmb1dVZ1IyV2NSU0t5dER6
        Njc4dVBFQlF2OHBEZXVGSjVaU0Q0eHNmU3RtUVNrVmFxdUVJNUZqbHJ3dkRmcGFm
        Yy8xSHVWNnd5UEZzaWxCR2NrcjJvVVdHclN0VnNhQ2NsakY0LzBKMlB1cTVJUDZY
        YVQ4SjI1by9xbGtBTGdKSTh5YkRWY1NqdS8xTWtIY2tyRW5meWJwbUhIVnh4S0NW
        d3Zkckpnc0UyUThMSndNVWFrVEZEKzhFUmpnSEhjd2tZR01PUHFubW14YWUrVUcz
        NDFuczU2NjVSam4wYmVJS0M1RTdhQVZ2a3J6M3RVb2ZqejE2cW52aGdoVGdNRXJ3
        MS9zQ3dGd0phWW0zUVBEZmZQSHRlMGV5RGQzMkQzSUlYRnFQcUxjdFY3UXNqT3NI
        T2JFOGNYaG9LYkE3ZlRUZkNxNFNFdlJGUmVSZStlSTFsZlJrQzdmUGdaU2lmN0Rt
        ck42UjcvTm1MQkEwZG9udUFRRDFiWEI3dWVJK1VkQ3FxKzZWRURVMkp6Y3ZXRlZB
        YjRQV0pvbU9JYnhwRmZrTGZrUkY2UHM3bENSUXplSmw3cC9pWkJoRUVqYjdMYlVV
        bnBUWWFLK0Y3UXJVR1V1R2FhUS95WC9pcmp6d1BGWUtSYkEwRkJxejdCK2JsUm1m
        MXhnZWxlWjVLSkRzcmd3WlFyMERsa0QydzIvYkJxMW0xNUt6bXk0WFBUSjN5NlpR
        NmpYYTRNeW03aWZNWnhtcW5UUW93SkpJMi8vaFJiVFhZOXI4MFZVRCt0Zm5qcjhu
        ZEQ3eVc2a3N5ZDkxcnV6aXIydHAzQzhRU2lGU1g2RFpaeUVpang5RUk3SlJJdwpJ
        YVo3bUxLL3lWTmtsZ0lnblpHNEcxaUZobFoxTXJXZk43TThidWs4UUZzCi0tLSBo
        dUZhOGQxUnNTMHpkWGwzQnVWMVBoZkhhSENYY0VUR2xuRDBPZlhwbjFVCrMene6t
        bsn0Xl7UASHLMfGV0qcWShFJPvXVglukDynFrIGOnK2JfCGchT+NKskJZcIIZcxX
        azQYmliD8JWyLnA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14wqvmn43wc3tquc22uyme4sgy0kyswdzcqlqj5xax2ftqsdwfs24s8a48f8nc0k6xp8a844zq3x20sj3p5q4htg203sy0am3ccng7369nm0mfjqt5lp9f2grzjsev7ktyl0zj9puz260864l0kktswsgwrwr8jyw2jurxjs2f7ys8mpg8urxfjfw5wggyeskg5j34x32hhtnk2kpugj4k3vx07s3a7desr08rn46jk03mc4qhkdq76sf0jgy02m76uz9l5y7rjd34y4vy5znya3j5q8q74sq2pqffy7uxcxrctuzgywvwdwptwq9yehchmhskgt56yfhedgae0nt489n3ld824tf73efvsgset2kkdneqtaaqs5t2zzk072jal2eg60n3e7adrjwgkvpdr99jleckkm48g7urry8v35s47v32a5qa75yk486sz650vxnany0jxjrl69kzsx38d4sg8ph4ccsf5f3sqexqm7fds55ckk7s958v2uhcwcqguve2f2k82g5yfzz8n9kllzjw5y9y485xguawkw0clqh3k5s4a06jya2esejuxjatccf4jznf55f4xjvwjj52gg38l3ksa8jfp3mvxqy0324nkaslnm96k56ve0ekjung42jpwjmuhmrnq22ynmq8ffk2wv5rd5578gvtt09hqr0x9h0lznjy5s6p6q9xqfhpc05g5h9k63grec3amvny6y8jjkpfqgpuhxk24ejs93ech3s5ycqj3w3djs52x2pksu9lvczz66z49vruu2uus4tapncmkxm4p905j7qr2xq62z8df6vhf3ugxcekngqvc6g0y958s3vnzs9w6vaj0v4vddke4thuwr5rc033r7v8tgjg6jw6u3e7kqyfjqjnkdy5x3z9ww5d399fw6sjs5sf23lty4x6a6v9nyt4043yq6fprajg9rtu77x2qth6stfl896va5p59hcguv5079pmlgc25a8zuwrzhjvvxvarc5qjcgt7fa8h6aacr7jax529f68gv2vm37ejphlssxe928rkuezdzur7pzpem6e2jrrdqrvnq39mwd85lm5ncgkxdaz0d67mcza9msmerv8jfcs88y7w48zk4k9wutsasgfekdkjq9r23xgczgplvfga9hxzxm2z6xvmjmp7hquc95gmckpv5vzvux7hxjws2tl8z2vgm6vckhvq8rfljc9f0qdq6wy2w8sxl3mp25g5sd3h9afaa5ggd7g98wkryqh537a0faa359mh722seg6f0ssqwzm7y49vjvjra46yjc3zwqzp0ygc3gtnrrhs9yesm56frevzprd3yytqm4thv3fhdmexgv465a950xvlptk4s0hte6wzzskyj3scdtf0qjkjv25tn5ggc85wfadngz6jpjhjgm5c44ad3uqhgancst7f5dhw7dt5qs0q5p0ffaaejj9pv99fqegrypejzuuffhajpprtm9frx795umkwd2rgzhyxwnrez2z8yyvcctgenslapqq9uyzjk2t3hus43sfpxcg8fakques9kpy4v5pck4t2ajn8gtph3pquva984pqjq7mwxzh3sth5qdc722g5zztsxc90qy8sf4844p2k84kjv7jczymzhxvf2aqpfm2jgyze2qk8euzkx9l553nfaayue5el3dhyus8gu2cjfme4jzknl6p9zshr2cg4wfpz45t3xr2qh4tqplcvgqh0shye9rza2rek4j2ashjrrf4f8k7p2d32u6tq7v38j9jzn2lqw05m0q746q23kfvl2mxsyqant2uhg0fhzngete8kjcc0ughw7hluzklsqxwz3f5m9qvy9qrdfrmq22s7n4wqvrts3wtzhxpe09ngzlc76qmam7jlkrx59834ngt5w2j4wjk85wvrjrnzzra4nf2m2hdv8nswvhf39lr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T08:35:50Z"
  mac: ENC[AES256_GCM,data:TdTYJCzphu8pHz4XW+OaCNXzVO17pcZvQtUjri3R2v4kR5MmQ3ic7n5MIWKfd3FAPkvo2cx69s+zfG2pfPHTphis6nfDA7dAhlltX3v+CspE1jst4rFbGziPIeZvzgLP0ixLMb0L+XSksY06SmiETAVe9rB/N9KGcM1crCRxBcs=,iv:3fOMMIgLeGF2JqMRu7qRMxMhBqytPQqpbBHipQpB/3U=,tag:M07W1NRCLeRrg3EQ9y4mtg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
