# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-access-token
stringData:
  token: ENC[AES256_GCM,data:WP2AP0ezkrCK5kIDPUO4IuACLtvtE8GxOktNx+zzef+iVCdr18uCx5a+C3h9b5OYfMO9qKPK6swwXwqcJbluFnX/Vx41/pZwzbBgPLEz3VJ7S804wwZNoI3DLyPfCg==,iv:F4kLtdThvLR0gK8uvqwNSqCJxTexHFJLoRII7FX4xO8=,tag:uZXCJz5sxnDaB46XIK5qSw==,type:str]
sops:
  age:
    - recipient: age17kkjwh97ech8ky6sa05xnyuxr9gpqwdjq8wjqc55a2mu7mdv9s8qvdfxpv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseXhhM2RjUGd1alFlMWNE
        OXYxMjVGOWcvMTZJdUZidUJQTUlBbEJ5NlNJClYrekFJbkw1a2ZRYlhKNHFGNDda
        QTIvc0VkTGd6MFA5ZEMvNjhBSFlvQ2MKLS0tIGZtZktTSzU1WHpZQ1pvZklpQ1hN
        L0FQakg5TTNIMGhqd01Dd0daQVBPc3MKV78FRjziK7DTNsayONzigYGRGsOGgHS3
        6k+QGdo2KikUKeWzNqeAmiHzjOJDTCxAHYmZeZ2jkdWJHUx+6HI+Ow==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-02T07:03:07Z"
  mac: ENC[AES256_GCM,data:VswmN35Prjqpfc/tspEofu4uh/FayyAkfOKWZ03IdSTsXjJDA7/8tseThG5hQRS//Rx8WfvTK1/uoPGPp4h7sZvLEm18eAfuiGwdxRRfySf4kk6XWYV5QWV6yI0EbdwkCzvqh6Jstqa7vVVRyJ3yFgi5+bKIpwUnAZM7XDogphE=,iv:dgbcY2h0E3+xbrnttQJJkTnmXDayIGw1wc2jMn0bNB0=,tag:NL8cCwMsRSfyFOg30VjnMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
