apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:2kgpMLdA3fBs3mYHHNE+jl8TNFUZiFzF5mFbUuE961/HWwiWqs9xZg==,iv:QVZtXLYeZSkVs/8kaH1WRaFCb0B6LXnPggFa8NxH3Sw=,tag:Nkrro93MJO4rCYnGN3un4w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHUxT1YwNFhh
        VUZLZUw0ajlmRUsvRitna2ZDeUpEaERaQUthN2tMTlQ4SFRMQTBSbjl5TExyRVpr
        Y2lVcFBidmtSUlpJYTVtbXBkdmVlQ1J2ZUFOUnpWTzVSZzBWaXVCOHJjSjBYb3Jn
        eFZ2TDltQk9Pc3FGdFZRR1hwRkFCMnAvaFB5Nis2RTQ2azJXNVg1REV2T2NiWW1T
        OGJIZzZUWVlLQXUrQmRXWmxPMkExUFhjaWhaTnRGSnJBV3MrZjc3eHYzbUNYNXNB
        OXhjNDZvNEFBL0xBbWZIZU1aQTBYc3FqUFptK3RYRHJNODZWUWJJL3BDZi9kdGlo
        bjZ3aEJpV0RoK3RrZFlFUHpyNDFxdlZ6Qi9GSEV1RDFGY0s5ZXVwZ0NPOThwdHow
        b0diZXZ3Yk0veDNmM3RPdE54ck9zS3Y0Nk1oc283b3MxdzM5Zmw5c0FLeXlLVHNs
        amtjTUVjYWpQdkdBd2hKN28vQmRCWW5UbTFsSmd5bXd1ekIxYW1VQTNXMWxKblJF
        dkZ0OWFCL0RtcjVMR281KzFMSkluSEJoK0FFWXZKbWZYTjJVNks5NmsyRTJObUNP
        Yk9DZ1VHZ0g2cXBSSitsK0VSa2RxV0lLOG9JS1krWnl2SllBeWpweXBsYzNtUDZC
        NTVFcHpHWEhzV09qaHZiNzVNQU94YkFUSStxVXZaVWsxYTVoWERKWERpRkd0UkZx
        R2l2SEVqTUtUUC8yWEpRK2tHZnd0TllRZjNxRjh5M3BtSko1aGI4MkFlWEt2UlpS
        aTdmOXBVYXJ6NlZpNVdpN2Z1MXYxa3d0ajB4M0F5ZmJtdmVPL1EwZlhwd2pFYWoy
        WVdJZnFScWlDY0o0TEdsc05nNCtobzFlZHNWT3AxVFIvdzdIQlZhZkpuZFkwS1Bv
        bmJnTTErWkd6bHNhRk8zOFg0TDcrQ2ZBbTh6dVZXcUh3Q242ZUdVbXdKZW1qdW5q
        SkJhYjBPQkZUSWxBY2EyZE85QmM0bWdMR2ZEbkVORUFURDFGUktMQ3ZCZEovL3pS
        WHF6M3BvV05xVTgwUGN6c3V5SktsLzVPc29UVnV4ZUZXT1ZmdWxEVElvZE96RHll
        bXZPZFBOU2xBUzQwQk9tTHBmZzd0UTdpeTRKTDBrOEh6U0dLZ3hzem5LUk1DamZF
        My9nMktvcHZ2UzZ4N3VUK3Z4U2xHVnc2R1FVQncrMUNXdnFuR3I5U21vQWY2aWY3
        ODJqMG9QYXJvUGZjemtJRnV3VUduZmhORktmcW9CMjk3Nm1oOUpoNVc1VXEvKzdX
        UWpvcWdFQ0dNTWJVUjVRUmVYSG84bDJtbjkyMXJ3U3ExSDVya0VRUVc5QjA4aFA0
        MUZDSTVnMkNvNXV2cnBkbjFQd2llbER4cUlCYmJsSXFwTCt2TlVPMU1kOWZsbStj
        alJtVldVSXdlNThkaGxlOXBtdmI0TDc0ZHdyOXd0MDRhRVYxdzBFZnN1ajR4UExC
        Sm12clBDUVhDM2ZQWXZDNnFtZ1BUVkxkcC9RWVI5TlJxYm81bnVFU2M4ODU1aW1M
        MWJIRnE0RkhCcnRWZFpPZUpjZ1drK0dSTXh6UmFnbWtyQXJjOTlNS2dIaVhtdnJH
        dDlTT1FUT3NYWkVQTUNQUU01S25nWGYyTlplbHF0TkNYY2xRUnNjYWYwdHFHR2pX
        K3dyVEVWQzFiaGJHZW8xM2lCZkdDQlY0bWNIODFobVVuSk4xV3UxQjZvbHlYU1do
        SFdGa1kzR2gyNXBpQk1OVWovVHBRZERaNXRoYjFtdzJ3RjNmdHladEIrZVdOTUNu
        ci9Oek9YazNQOFBuWW1ZN2pkUTd5VmtIZHdDRlpoSkNFZWZvYVZuNUdzWjVZMkRw
        aXJoT1hvbkVCZUN6R0dIMDAzUE5mVGtOYzlEMWNNNjJvMXVuMWNUZysycVRZT01O
        dHZkbUpGclRYOUFjVTlRSzBMczJHenc3ZGE5U2tXaks2cFR6cjVra3pGZEtZUQpU
        L25FbEtidkR6MTRkS3EwSWtxa01hZ0Y4TWlnY0FjakZZcDdJSWV3M1pvCi0tLSAx
        ZlYzaXhHZ0tRZTRMczNOaTNZZ3lmVEV5cXhkSnA2ODZiUVR5Z09VV2lVClYVk6Kf
        RP5tRn9G6S0mbMV9xLUm/axi1P+HbRfiEV0GKRP8S7PyFD000SPv79OmMNZ3n4dg
        8TRTZmWrY+QZqFM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14wqvmn43wc3tquc22uyme4sgy0kyswdzcqlqj5xax2ftqsdwfs24s8a48f8nc0k6xp8a844zq3x20sj3p5q4htg203sy0am3ccng7369nm0mfjqt5lp9f2grzjsev7ktyl0zj9puz260864l0kktswsgwrwr8jyw2jurxjs2f7ys8mpg8urxfjfw5wggyeskg5j34x32hhtnk2kpugj4k3vx07s3a7desr08rn46jk03mc4qhkdq76sf0jgy02m76uz9l5y7rjd34y4vy5znya3j5q8q74sq2pqffy7uxcxrctuzgywvwdwptwq9yehchmhskgt56yfhedgae0nt489n3ld824tf73efvsgset2kkdneqtaaqs5t2zzk072jal2eg60n3e7adrjwgkvpdr99jleckkm48g7urry8v35s47v32a5qa75yk486sz650vxnany0jxjrl69kzsx38d4sg8ph4ccsf5f3sqexqm7fds55ckk7s958v2uhcwcqguve2f2k82g5yfzz8n9kllzjw5y9y485xguawkw0clqh3k5s4a06jya2esejuxjatccf4jznf55f4xjvwjj52gg38l3ksa8jfp3mvxqy0324nkaslnm96k56ve0ekjung42jpwjmuhmrnq22ynmq8ffk2wv5rd5578gvtt09hqr0x9h0lznjy5s6p6q9xqfhpc05g5h9k63grec3amvny6y8jjkpfqgpuhxk24ejs93ech3s5ycqj3w3djs52x2pksu9lvczz66z49vruu2uus4tapncmkxm4p905j7qr2xq62z8df6vhf3ugxcekngqvc6g0y958s3vnzs9w6vaj0v4vddke4thuwr5rc033r7v8tgjg6jw6u3e7kqyfjqjnkdy5x3z9ww5d399fw6sjs5sf23lty4x6a6v9nyt4043yq6fprajg9rtu77x2qth6stfl896va5p59hcguv5079pmlgc25a8zuwrzhjvvxvarc5qjcgt7fa8h6aacr7jax529f68gv2vm37ejphlssxe928rkuezdzur7pzpem6e2jrrdqrvnq39mwd85lm5ncgkxdaz0d67mcza9msmerv8jfcs88y7w48zk4k9wutsasgfekdkjq9r23xgczgplvfga9hxzxm2z6xvmjmp7hquc95gmckpv5vzvux7hxjws2tl8z2vgm6vckhvq8rfljc9f0qdq6wy2w8sxl3mp25g5sd3h9afaa5ggd7g98wkryqh537a0faa359mh722seg6f0ssqwzm7y49vjvjra46yjc3zwqzp0ygc3gtnrrhs9yesm56frevzprd3yytqm4thv3fhdmexgv465a950xvlptk4s0hte6wzzskyj3scdtf0qjkjv25tn5ggc85wfadngz6jpjhjgm5c44ad3uqhgancst7f5dhw7dt5qs0q5p0ffaaejj9pv99fqegrypejzuuffhajpprtm9frx795umkwd2rgzhyxwnrez2z8yyvcctgenslapqq9uyzjk2t3hus43sfpxcg8fakques9kpy4v5pck4t2ajn8gtph3pquva984pqjq7mwxzh3sth5qdc722g5zztsxc90qy8sf4844p2k84kjv7jczymzhxvf2aqpfm2jgyze2qk8euzkx9l553nfaayue5el3dhyus8gu2cjfme4jzknl6p9zshr2cg4wfpz45t3xr2qh4tqplcvgqh0shye9rza2rek4j2ashjrrf4f8k7p2d32u6tq7v38j9jzn2lqw05m0q746q23kfvl2mxsyqant2uhg0fhzngete8kjcc0ughw7hluzklsqxwz3f5m9qvy9qrdfrmq22s7n4wqvrts3wtzhxpe09ngzlc76qmam7jlkrx59834ngt5w2j4wjk85wvrjrnzzra4nf2m2hdv8nswvhf39lr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T07:12:03Z"
  mac: ENC[AES256_GCM,data:+8+K2KtkmvkDVsHKk+WzS4Kw4Z+FoJkZmCjkxW8JmxTk29k2w6ExJPrcon7yqDwgJlLM92iSxZPxOHQZcJnmH7GAutfZea8vlvmw3zkgQ71h2FVngSfAQoC8CmRCtU84cAy6dlOnfJJ0PCW2u+rq2vroeIXCkIdClrh/TBKCz2E=,iv:OlNh4y9+KZUVggNpLE2GmqVItxxSF/h7vO288MGJCYE=,tag:YK5yWHLe20dlt68IwzfNnA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
