---
groups:
  - name: mosquitto
    rules:
      - alert: EmbyDatabaseBusy
        expr: |
          sum by (app) (count_over_time({app="mosquitto"} |~ "(?i)retry busy DB"[2m])) > 0
        for: 2m
        labels:
          severity: critical
          category: logs
        annotations:
          app: "{{ $labels.app }}"
          summary: "{{ $labels.app }} is experiencing database issues"
