---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser
type: basic-auth
stringData:
  username: ${POSTGRES_SUPER_USER}
  password: ${POSTGRES_SUPER_PASS}
  POSTGRES_SUPER_USER: ${POSTGRES_SUPER_USER}
  POSTGRES_SUPER_PASS: ${POSTGRES_SUPER_PASS}
# ---
# # yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/external-secrets.io/externalsecret_v1.json
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: radarr-user
# spec:
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: bitwarden-secret-manager
#   target:
#     name: radarr-user
#     creationPolicy: Owner
#     deletionPolicy: "Delete"
#     template:
#       type: kubernetes.io/basic-auth
#       metadata:
#         labels:
#           cnpg.io/reload: "true"
#       data:
#         username: "{{ .SQL_USER }}"
#         password: "{{ .SQL_PASS }}"
#   dataFrom:
#     - extract:
#         key: radarr

# ---
# # yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/external-secrets.io/externalsecret_v1.json
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: prowlarr-user
# spec:
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: bitwarden-secret-manager
#   target:
#     name: prowlarr-user
#     creationPolicy: Owner
#     deletionPolicy: "Delete"
#     template:
#       type: kubernetes.io/basic-auth
#       metadata:
#         labels:
#           cnpg.io/reload: "true"
#       data:
#         username: "{{ .SQL_USER }}"
#         password: "{{ .SQL_PASS }}"
#   dataFrom:
#     - extract:
#         key: prowlarr

# ---
# # yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/external-secrets.io/externalsecret_v1.json
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: sonarr-user
# spec:
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: bitwarden-secret-manager
#   target:
#     name: sonarr-user
#     creationPolicy: Owner
#     deletionPolicy: "Delete"
#     template:
#       type: kubernetes.io/basic-auth
#       metadata:
#         labels:
#           cnpg.io/reload: "true"
#       data:
#         username: "{{ .SQL_USER }}"
#         password: "{{ .SQL_PASS }}"
#   dataFrom:
#     - extract:
#         key: sonarr

# ---
# # yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/external-secrets.io/externalsecret_v1.json
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: jellyseerr-user
# spec:
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: bitwarden-secret-manager
#   target:
#     name: jellyseerr-user
#     creationPolicy: Owner
#     deletionPolicy: "Delete"
#     template:
#       type: kubernetes.io/basic-auth
#       metadata:
#         labels:
#           cnpg.io/reload: "true"
#       data:
#         username: "{{ .SQL_USER }}"
#         password: "{{ .SQL_PASS }}"
#   dataFrom:
#     - extract:
#         key: jellyseerr
