---
apiVersion: v1
kind: Service
metadata:
  name: &app postgres
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres.${SECRET_DOMAIN}
    coredns.io/hostname: postgres.${SECRET_DOMAIN}
    # lbipam.cilium.io/ips: 10.12.1.10
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres
    role: primary
