apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Hd9zj2n/lTNg,iv:JvbbR50Lo/uCn7fMw8FvtNsahhkzxj1Xlmwpfl1c7Tc=,tag:mSrql7EK1KsrHehTfDy+Qw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFpxTnBzakdi
        bDluYmJUVUdEajUzdzVKSjlUL1hGZHowRU1jbnJiNU5hQVM1RGoxaHlTeEc2UDJj
        NFZSU3kxQWlPSmw1UVFGa0VwTm5vb2FaYXdkczhyMzlkNnhjN1V1eEhxQkp4aWZk
        NlF3RlBRNXBBZ09nWnpTWUJwRTJ3aFMyeE5NSStib3F0NnJrSGMxM1FCVE8vMTJK
        OGw0blRCOFByUWVsaUJRTlBkKzgxSzM5M3FEMU14MDhRbGx0MW5WS2hLOXBURGlh
        V1ZBeStORm9kcG1NMmRabmRoWVBTUGZmZU5oaDZENEVlRFpNS3kvbnVIQVhuR256
        ZVhzMlFUL2g2NFlCb1lBSURmeHRvcVlDZlR5Y25BMW5sZGN2MzA1TWlyOXZ1YzFI
        NEdxZGRSLy9UcW0wTEg0aHg4WGRwU1NxUVkxckd2T2xMaThOeXk3ZWtyODZWa2pP
        bVZodGRxcUZ0QllUZHdXOVlxQlZ4c3NpcVM3Rm95TU5VWnFqTnV1RVovL2lYbE9S
        NjhLakExcUhubnZaM2ZEaGJFZzdoZ3lkdFpYVkpHVmhyRm95azB3ZWlhRHpPa1FG
        L1I4MytxY3NFaGJEVmhOaFFZQmZCdEpKb0JhUmRnWFpDZVgxZGxXNnRuRDlLY000
        OGNhL2pxY0hDcXJlYUMxTEhHUTdLMytORjBOVEcwVi82L1pqbmF0enV2Z084a0d1
        bUVuSzBHZWtWMVhhdi9UdWF5aGJHQVZCNU9yT2lBb3dLV1o1K0xMWTRzQ0Vaenk3
        RUZuZ3RNVnJOanRTY3Y1bC9tcjJrZGlqaDVRL3B3a2YwMnBlUWRDK2hUd3llTXRF
        WGNnN0FudWx0Wm91TzQ1VVVqY1A0dWZGWFFyRWswRWpJNzZyTHpvczNKTUhCZEdX
        NFdJc1hlZ2I0L3Q4QXJndzlDSHVDNEllZjk2NEJsTmJtU2xPbmxKb0hra0VwN0Y2
        MUVtTVNCTzFzdnlvbVRWVVpBdk1KeWtqejJCQ2Z4V3RkcjV5bGJOQ3BzRlU4MWFG
        Wk52d0NQYVFyN1gwcEhXd28wNjROUnh2eXZTODhQemkvTlRSLy90aU9ITGlaVTlQ
        R3psYzJFYTI2M1FMUnJtRC92ZDJCU2tpbXl6UEt4bzh6UUJqcS9qUGsyZ0gzOEV1
        UzZjaUY1a1JTeVcwR01BWlZZcDJGbzRickZCUUN0V1g5S0RxanB0dGFyOHlWb2Zl
        cUt0L3lSdFlKOWovbThIQTZsMmNMajVWQnN5VUhYZ3IrTmJUWmhFY1czek9SNzZp
        NTRONlFCakNzY1hUNXBvVG8rdzRSTW1pUndOZW1XWXVwNCtkQnRyMGJVbDI5a1By
        RWQ1MHBxV0xaY0R5c3ltODk0MDRoQ2p3Q1JmQzk1d1EwTmRIM0tTYjZiN3hqVVpM
        WjJzR0hWRzNBbXdLSWJsYmVobFVpZGwvU0NvaDhYc0VPbnIya3hqTkVjZTlxRWFJ
        YVBFbVBDMlFrdTNpdHVEUHhaNGwydkN4Y3RreThtOGx6ZGVETDJGbmZDQ2V5SGZP
        bkpVaTR0bzVBV3Q2NllKQlVRNkszbjNxeEtGcmFuc1JrME5zWU9CTHhiY3VyLzRW
        OGlFMUZadWJ4ay9IQ2s3bk8xTG91RDhZVVdxWWRqNC9RdGFXYm1hem1CWVJpMWJs
        UDNMYUdoZUZHRnhEWEpLYnBWQlJlNm5NWm55Q25XSWZ4ajlZMU5pa0lzcjlyYW92
        NnR5UGRmZHFpYnNBVzJkcDgyV3A2ZUxpcUdBYmJwdHlzajNXczJpbGVXNmphN1gz
        VUxPWThIYzNpWFM4dENPMFZyeHVNbzNVd1prY3JZdzJiek1pVjlUZWhZTjNNVzNR
        UExXQUtiM0VzbXNuVFJrNStzNW5JUnIvQ0hPY2xnWjlQRStGYlVLaGhEd3UyR1ly
        WGMrc255U2tjb2V5MUwxZ3o3b1lTdmprMy9wYVhjSjVmQlNTTnpwbGU0KzFaUQp2
        eXh5OWNjTnpyL0YxSzNvZ0dMY3VrT1F6alVLQmtTcmZCRmUvTEwrc25vCi0tLSB3
        Njg2Y1Y1QkpvalJwVG91TkU5OTJVVHBzNTlVV2VDZlk1OW9NYlppK3pNCmCqexUj
        a7OyOIt7XjX3wRSDnA+dexxdpsF5+SzWngRHBWCw5FzclszU4GBzLspcBHJMpKuP
        iAXpQmoh64zISOU=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq14wqvmn43wc3tquc22uyme4sgy0kyswdzcqlqj5xax2ftqsdwfs24s8a48f8nc0k6xp8a844zq3x20sj3p5q4htg203sy0am3ccng7369nm0mfjqt5lp9f2grzjsev7ktyl0zj9puz260864l0kktswsgwrwr8jyw2jurxjs2f7ys8mpg8urxfjfw5wggyeskg5j34x32hhtnk2kpugj4k3vx07s3a7desr08rn46jk03mc4qhkdq76sf0jgy02m76uz9l5y7rjd34y4vy5znya3j5q8q74sq2pqffy7uxcxrctuzgywvwdwptwq9yehchmhskgt56yfhedgae0nt489n3ld824tf73efvsgset2kkdneqtaaqs5t2zzk072jal2eg60n3e7adrjwgkvpdr99jleckkm48g7urry8v35s47v32a5qa75yk486sz650vxnany0jxjrl69kzsx38d4sg8ph4ccsf5f3sqexqm7fds55ckk7s958v2uhcwcqguve2f2k82g5yfzz8n9kllzjw5y9y485xguawkw0clqh3k5s4a06jya2esejuxjatccf4jznf55f4xjvwjj52gg38l3ksa8jfp3mvxqy0324nkaslnm96k56ve0ekjung42jpwjmuhmrnq22ynmq8ffk2wv5rd5578gvtt09hqr0x9h0lznjy5s6p6q9xqfhpc05g5h9k63grec3amvny6y8jjkpfqgpuhxk24ejs93ech3s5ycqj3w3djs52x2pksu9lvczz66z49vruu2uus4tapncmkxm4p905j7qr2xq62z8df6vhf3ugxcekngqvc6g0y958s3vnzs9w6vaj0v4vddke4thuwr5rc033r7v8tgjg6jw6u3e7kqyfjqjnkdy5x3z9ww5d399fw6sjs5sf23lty4x6a6v9nyt4043yq6fprajg9rtu77x2qth6stfl896va5p59hcguv5079pmlgc25a8zuwrzhjvvxvarc5qjcgt7fa8h6aacr7jax529f68gv2vm37ejphlssxe928rkuezdzur7pzpem6e2jrrdqrvnq39mwd85lm5ncgkxdaz0d67mcza9msmerv8jfcs88y7w48zk4k9wutsasgfekdkjq9r23xgczgplvfga9hxzxm2z6xvmjmp7hquc95gmckpv5vzvux7hxjws2tl8z2vgm6vckhvq8rfljc9f0qdq6wy2w8sxl3mp25g5sd3h9afaa5ggd7g98wkryqh537a0faa359mh722seg6f0ssqwzm7y49vjvjra46yjc3zwqzp0ygc3gtnrrhs9yesm56frevzprd3yytqm4thv3fhdmexgv465a950xvlptk4s0hte6wzzskyj3scdtf0qjkjv25tn5ggc85wfadngz6jpjhjgm5c44ad3uqhgancst7f5dhw7dt5qs0q5p0ffaaejj9pv99fqegrypejzuuffhajpprtm9frx795umkwd2rgzhyxwnrez2z8yyvcctgenslapqq9uyzjk2t3hus43sfpxcg8fakques9kpy4v5pck4t2ajn8gtph3pquva984pqjq7mwxzh3sth5qdc722g5zztsxc90qy8sf4844p2k84kjv7jczymzhxvf2aqpfm2jgyze2qk8euzkx9l553nfaayue5el3dhyus8gu2cjfme4jzknl6p9zshr2cg4wfpz45t3xr2qh4tqplcvgqh0shye9rza2rek4j2ashjrrf4f8k7p2d32u6tq7v38j9jzn2lqw05m0q746q23kfvl2mxsyqant2uhg0fhzngete8kjcc0ughw7hluzklsqxwz3f5m9qvy9qrdfrmq22s7n4wqvrts3wtzhxpe09ngzlc76qmam7jlkrx59834ngt5w2j4wjk85wvrjrnzzra4nf2m2hdv8nswvhf39lr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T07:18:43Z"
  mac: ENC[AES256_GCM,data:qTnS7gfCX79hQMvXyuJl3cbQcdjY6taKDwVV8q3YC6vgW4v+xeVqMeg7nOLyAVeED2KJ00koYWqjWuanLD1qAfroixg0wqa3WwtDE8tteWEroKLA63EBm2v95cM6OQh3gVtFagdxPpJbPnxazuv5HpXOIPEqDew7hA+/zQkXOaQ=,iv:S7mi74oi+tvCms7J2UEOsrekBgBdgM9VUBQl2aRV1hg=,tag:SPe0PPa4rOtKGX+mqM5Q1Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
