apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:aRKggHMk4g58,iv:Tac/sk58xNlDbeAkRVB9RORkTHElXawqGm0RSdCaV7k=,tag:rXty6fnz9nKT6dQNQbbSSw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsa1JWUDZPQ2hjTksyalB0
        aXU1UWU1L2xma3ZFZ2JPTEtZcWx2YSt2ZkRZCnJNdzJ3QzZFWUhHWCtIdjQxaytN
        cGpvVVNSZzJCUjJGeDVqOXBscVZ0emcKLS0tIEI5WUV0ZVl3QjJVcUFjVnZoM3E5
        RGFpU1dPWUxmM2prbVhXWjZqS214a1kKGcr7w1ND6VfM3P+C9EJf5RwvoUUdo0fu
        x8tpsx/NrWke2CJdYhGCyaiXYn+jCJAo1LyPo4BMBqZpQPkGrS4bAg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17kkjwh97ech8ky6sa05xnyuxr9gpqwdjq8wjqc55a2mu7mdv9s8qvdfxpv
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-14T16:36:56Z"
  mac: ENC[AES256_GCM,data:TDgmvJDH0vo6FF+lOCoIi/7b52684dTxum2T5a/qrJmmFfMIDmW48ffhWjzqEC3RO6TLMYdW2cxHZ+ydhnJ7mpyoLwUuDk5bYqS+6DwZE5nRAgIsi75Mj41P+2zamv2SgmCdYWRirOaEWxOHdcOqSkog8YYX+OWNxmASAX5yNH8=,iv:K4rbgh86ckzGI65wLw2O78cmrVnHA3PSNW3S6mdoX5Q=,tag:J07/U7d97vAjxS/xpb5lXA==,type:str]
  mac_only_encrypted: true
  version: 3.11.0
