apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:aRKggHMk4g58,iv:Tac/sk58xNlDbeAkRVB9RORkTHElXawqGm0RSdCaV7k=,tag:rXty6fnz9nKT6dQNQbbSSw==,type:str]
sops:
  age:
    - recipient: age17kkjwh97ech8ky6sa05xnyuxr9gpqwdjq8wjqc55a2mu7mdv9s8qvdfxpv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsa1JWUDZPQ2hjTksyalB0
        aXU1UWU1L2xma3ZFZ2JPTEtZcWx2YSt2ZkRZCnJNdzJ3QzZFWUhHWCtIdjQxaytN
        cGpvVVNSZzJCUjJGeDVqOXBscVZ0emcKLS0tIEI5WUV0ZVl3QjJVcUFjVnZoM3E5
        RGFpU1dPWUxmM2prbVhXWjZqS214a1kKGcr7w1ND6VfM3P+C9EJf5RwvoUUdo0fu
        x8tpsx/NrWke2CJdYhGCyaiXYn+jCJAo1LyPo4BMBqZpQPkGrS4bAg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-02T07:07:13Z"
  mac: ENC[AES256_GCM,data:qAO04/fNCVoNx7W3CpLyEVTwrff4UcdQ+EYqIGtp3JfSe/oEtSiLBmUjyRTzxLt9K6G/Gjmms962C9vqiicqo0V8xqIkyUea/ztcRoFwbHdqjxCDD+cPJ9X8bkQKWaPo6HQFg3myw8NQRlqTa6nz3yneaMKY2zUKZpNI7glrXQA=,iv:mX8bDuXujNUTy85ZWqABkC0p/tVElaDMfxhYrBKxO6k=,tag:GMGOV8M3L68PM2TOm1YtoQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
